"""initial_schema

Revision ID: 52a26446da45
Revises: 
Create Date: 2026-04-20 00:09:26.471397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a26446da45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name_en', sa.String(), nullable=False),
    sa.Column('full_name_ar', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('registry_number', sa.String(), nullable=False),
    sa.Column('registry_place', sa.String(), nullable=False),
    sa.Column('municipality', sa.String(), nullable=True),
    sa.Column('deceased', sa.Boolean(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_date_of_birth'), 'citizens', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_citizens_full_name_en'), 'citizens', ['full_name_en'], unique=False)
    op.create_index(op.f('ix_citizens_registry_number'), 'citizens', ['registry_number'], unique=False)
    op.create_index(op.f('ix_citizens_registry_place'), 'citizens', ['registry_place'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizens_registry_place'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_registry_number'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_full_name_en'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_date_of_birth'), table_name='citizens')
    op.drop_table('citizens')
    # ### end Alembic commands ###
