/**
 * Lebanese administrative divisions: Governorate -> District -> Municipality.
 * Municipality data will be added later per district.
 */

export const GOVERNORATES = [
  { value: 'Beirut', ar: 'بيروت', en: 'Beirut' },
  { value: 'Mount Lebanon', ar: 'جبل لبنان', en: 'Mount Lebanon' },
  { value: 'North Lebanon', ar: 'لبنان الشمالي', en: 'North Lebanon' },
  { value: 'Akkar', ar: 'عكار', en: 'Akkar' },
  { value: 'South Lebanon', ar: 'لبنان الجنوبي', en: 'South Lebanon' },
  { value: 'Nabatieh', ar: 'النبطية', en: 'Nabatieh' },
  { value: 'Beqaa', ar: 'البقاع', en: 'Beqaa' },
  { value: 'Baalbek-Hermel', ar: 'بعلبك-الهرمل', en: 'Baalbek-Hermel' },
];

export const DISTRICTS = [
  // Beirut — single district, auto-selected
  { value: 'Beirut', ar: 'بيروت', en: 'Beirut', governorate: 'Beirut' },

  // Mount Lebanon
  { value: 'Baabda', ar: 'بعبدا', en: 'Baabda', governorate: 'Mount Lebanon' },
  { value: 'Aley', ar: 'عاليه', en: 'Aley', governorate: 'Mount Lebanon' },
  { value: 'Chouf', ar: 'الشوف', en: 'Chouf', governorate: 'Mount Lebanon' },
  { value: 'Keserwan', ar: 'كسروان', en: 'Keserwan', governorate: 'Mount Lebanon' },
  { value: 'Metn', ar: 'المتن', en: 'Metn', governorate: 'Mount Lebanon' },
  { value: 'Jbeil', ar: 'جبيل', en: 'Jbeil', governorate: 'Mount Lebanon' },

  // North Lebanon
  { value: 'Tripoli', ar: 'طرابلس', en: 'Tripoli', governorate: 'North Lebanon' },
  { value: 'Zgharta', ar: 'زغرتا', en: 'Zgharta', governorate: 'North Lebanon' },
  { value: 'Koura', ar: 'الكورة', en: 'Koura', governorate: 'North Lebanon' },
  { value: 'Bsharri', ar: 'بشري', en: 'Bsharri', governorate: 'North Lebanon' },
  { value: 'Batroun', ar: 'البترون', en: 'Batroun', governorate: 'North Lebanon' },
  { value: 'Miniyeh-Danniyeh', ar: 'المنية-الضنية', en: 'Miniyeh-Danniyeh', governorate: 'North Lebanon' },

  // Akkar — single district
  { value: 'Akkar', ar: 'عكار', en: 'Akkar', governorate: 'Akkar' },

  // South Lebanon
  { value: 'Sidon', ar: 'صيدا', en: 'Sidon', governorate: 'South Lebanon' },
  { value: 'Tyre', ar: 'صور', en: 'Tyre', governorate: 'South Lebanon' },
  { value: 'Jezzine', ar: 'جزين', en: 'Jezzine', governorate: 'South Lebanon' },

  // Nabatieh
  { value: 'Nabatieh', ar: 'النبطية', en: 'Nabatieh', governorate: 'Nabatieh' },
  { value: 'Hasbaya', ar: 'حاصبيا', en: 'Hasbaya', governorate: 'Nabatieh' },
  { value: 'Marjeyoun', ar: 'مرجعيون', en: 'Marjeyoun', governorate: 'Nabatieh' },
  { value: 'Bint Jbeil', ar: 'بنت جبيل', en: 'Bint Jbeil', governorate: 'Nabatieh' },

  // Beqaa
  { value: 'Zahle', ar: 'زحلة', en: 'Zahle', governorate: 'Beqaa' },
  { value: 'Western Beqaa', ar: 'البقاع الغربي', en: 'Western Beqaa', governorate: 'Beqaa' },
  { value: 'Rachaya', ar: 'راشيا', en: 'Rachaya', governorate: 'Beqaa' },

  // Baalbek-Hermel
  { value: 'Baalbek', ar: 'بعلبك', en: 'Baalbek', governorate: 'Baalbek-Hermel' },
  { value: 'Hermel', ar: 'الهرمل', en: 'Hermel', governorate: 'Baalbek-Hermel' },
];

// Municipalities — North Lebanon (from official registry data)
// Other governorates to be added when data is available.
export const MUNICIPALITIES = [
  // --- Koura ---
  { value: 'Aaba', ar: "عبا", en: 'Aaba', district: 'Koura' },
  { value: 'Afusdiq', ar: "أفسديق", en: 'Afusdiq', district: 'Koura' },
  { value: 'Ain Aakrine', ar: "عين عكرين", en: 'Ain Aakrine', district: 'Koura' },
  { value: 'Ajdabrin', ar: "أجدعبرين", en: 'Ajdabrin', district: 'Koura' },
  { value: 'Al-Majdal', ar: "المجدل", en: 'Al-Majdal', district: 'Koura' },
  { value: 'Amyoun', ar: "أميون", en: 'Amyoun', district: 'Koura' },
  { value: 'Anfeh', ar: "أنفه", en: 'Anfeh', district: 'Koura' },
  { value: 'Bassirma', ar: "بسرما", en: 'Bassirma', district: 'Koura' },
  { value: 'Batram', ar: "بترام", en: 'Batram', district: 'Koura' },
  { value: 'Batroumine', ar: "بترومين", en: 'Batroumine', district: 'Koura' },
  { value: 'Bchamzin', ar: "بشمزين", en: 'Bchamzin', district: 'Koura' },
  { value: 'Bdebba', ar: "بدبا", en: 'Bdebba', district: 'Koura' },
  { value: 'Bdenaile', ar: "بدنايل", en: 'Bdenaile', district: 'Koura' },
  { value: 'Bennihraan', ar: "بننهران", en: 'Bennihraan', district: 'Koura' },
  { value: 'Bkaftine', ar: "بكفتين", en: 'Bkaftine', district: 'Koura' },
  { value: 'Btaaboura', ar: "بطعبورا", en: 'Btaaboura', district: 'Koura' },
  { value: 'Btouratije', ar: "بتوراتيج", en: 'Btouratije', district: 'Koura' },
  { value: 'Bursa', ar: "برسا", en: 'Bursa', district: 'Koura' },
  { value: 'Bziza', ar: "بزيزا", en: 'Bziza', district: 'Koura' },
  { value: 'Dar Bechtar', ar: "دار بعشتار", en: 'Dar Bechtar', district: 'Koura' },
  { value: 'Dar Chmizzine', ar: "دار شميزين", en: 'Dar Chmizzine', district: 'Koura' },
  { value: 'Dede', ar: "ددّه", en: 'Dede', district: 'Koura' },
  { value: 'Fiyeh', ar: "فيع", en: 'Fiyeh', district: 'Koura' },
  { value: 'Kaftoun', ar: "كفتون", en: 'Kaftoun', district: 'Koura' },
  { value: 'Kfarahezir', ar: "كفرحزير", en: 'Kfarahezir', district: 'Koura' },
  { value: 'Kfaraka', ar: "كفرعقا", en: 'Kfaraka', district: 'Koura' },
  { value: 'Kfarhatta', ar: "كفرحاتا", en: 'Kfarhatta', district: 'Koura' },
  { value: 'Kfarsaroun', ar: "كفرصارون", en: 'Kfarsaroun', district: 'Koura' },
  { value: 'Kfraya', ar: "كفريا", en: 'Kfraya', district: 'Koura' },
  { value: 'Kousba', ar: "كوسبا", en: 'Kousba', district: 'Koura' },
  { value: 'Metrith', ar: "متريت", en: 'Metrith', district: 'Koura' },
  { value: 'Qolehate', ar: "قلحات", en: 'Qolehate', district: 'Koura' },
  { value: 'Rachadbin', ar: "رشدبين", en: 'Rachadbin', district: 'Koura' },

  // --- Batroun ---
  { value: 'Aabrin', ar: "عبرين", en: 'Aabrin', district: 'Batroun' },
  { value: 'Adah', ar: "عداه", en: 'Adah', district: 'Batroun' },
  { value: 'Ajdabra', ar: "أجدبرا", en: 'Ajdabra', district: 'Batroun' },
  { value: 'Al Batroun', ar: "البترون", en: 'Al Batroun', district: 'Batroun' },
  { value: 'Al Heri', ar: "الهري", en: 'Al Heri', district: 'Batroun' },
  { value: 'Asia', ar: "آسيا", en: 'Asia', district: 'Batroun' },
  { value: 'Beit Chlala', ar: "بيت شلالا", en: 'Beit Chlala', district: 'Batroun' },
  { value: 'Bqosta', ar: "بقصطا", en: 'Bqosta', district: 'Batroun' },
  { value: 'Bshaleh', ar: "بشعلي", en: 'Bshaleh', district: 'Batroun' },
  { value: 'Chatine', ar: "شاتين", en: 'Chatine', district: 'Batroun' },
  { value: 'Deir Bela', ar: "دير بلا", en: 'Deir Bela', district: 'Batroun' },
  { value: 'Douma', ar: "دوما", en: 'Douma', district: 'Batroun' },
  { value: 'Hamat', ar: "حامات", en: 'Hamat', district: 'Batroun' },
  { value: 'Hardine', ar: "حردين", en: 'Hardine', district: 'Batroun' },
  { value: 'Jran', ar: "جران", en: 'Jran', district: 'Batroun' },
  { value: 'Kfaraarabi', ar: "كفرعرابي", en: 'Kfaraarabi', district: 'Batroun' },
  { value: 'Kfarabida', ar: "كفرعبيدا", en: 'Kfarabida', district: 'Batroun' },
  { value: 'Kfarchi', ar: "كفرشي", en: 'Kfarchi', district: 'Batroun' },
  { value: 'Kfarhelda', ar: "كفرحلدا", en: 'Kfarhelda', district: 'Batroun' },
  { value: 'Koubba', ar: "كوبا", en: 'Koubba', district: 'Batroun' },
  { value: 'Kour', ar: "كور", en: 'Kour', district: 'Batroun' },
  { value: 'Ras Nahash', ar: "راس نحاش", en: 'Ras Nahash', district: 'Batroun' },
  { value: 'Salata', ar: "سلعاتا", en: 'Salata', district: 'Batroun' },
  { value: 'Shbatin', ar: "شبطين", en: 'Shbatin', district: 'Batroun' },
  { value: 'Tannourine', ar: "تنورين", en: 'Tannourine', district: 'Batroun' },
  { value: 'Tehoum', ar: "تحوم", en: 'Tehoum', district: 'Batroun' },
  { value: 'Zan', ar: "زان", en: 'Zan', district: 'Batroun' },

  // --- Bsharri ---
  { value: 'Abdeen', ar: "عبدين", en: 'Abdeen', district: 'Bsharri' },
  { value: 'Baan', ar: "بان", en: 'Baan', district: 'Bsharri' },
  { value: 'Bazoun', ar: "بازعون", en: 'Bazoun', district: 'Bsharri' },
  { value: 'Beqaa Kafra', ar: "بقاع كفرا", en: 'Beqaa Kafra', district: 'Bsharri' },
  { value: 'Bkrkasha', ar: "بقرقاشا", en: 'Bkrkasha', district: 'Bsharri' },
  { value: 'Bsharri', ar: "بشرّي", en: 'Bsharri', district: 'Bsharri' },
  { value: 'Hadath El Jebbeh', ar: "حدث الجبة", en: 'Hadath El Jebbeh', district: 'Bsharri' },
  { value: 'Hassroun', ar: "حصرون", en: 'Hassroun', district: 'Bsharri' },
  { value: 'Hdad Shaayt', ar: "حدد شعيت", en: 'Hdad Shaayt', district: 'Bsharri' },
  { value: 'Qannat', ar: "قنات", en: 'Qannat', district: 'Bsharri' },
  { value: 'Tourza', ar: "تورزا", en: 'Tourza', district: 'Bsharri' },
  { value: 'Ayoan Al Bir', ar: "عيون البير", en: 'Ayoan Al Bir', district: 'Bsharri' },

  // --- Zgharta ---
  { value: 'Ain Tourine', ar: "عين تورين", en: 'Ain Tourine', district: 'Zgharta' },
  { value: 'Aito', ar: "إيطو", en: 'Aito', district: 'Zgharta' },
  { value: 'Arbaat Qazhya', ar: "أربعة قزحيا", en: 'Arbaat Qazhya', district: 'Zgharta' },
  { value: 'Ardah', ar: "أرده", en: 'Ardah', district: 'Zgharta' },
  { value: 'Arjish', ar: "أرجش", en: 'Arjish', district: 'Zgharta' },
  { value: 'Ashash', ar: "عشاش", en: 'Ashash', district: 'Zgharta' },
  { value: 'Ayal', ar: "عيال", en: 'Ayal', district: 'Zgharta' },
  { value: 'Banshie', ar: "بنشعي", en: 'Banshie', district: 'Zgharta' },
  { value: 'Basliqit', ar: "بسلقوت", en: 'Basliqit', district: 'Zgharta' },
  { value: 'Darya-Bishnin', ar: "دارية - بشنين", en: 'Darya-Bishnin', district: 'Zgharta' },
  { value: 'Harat Al Fawar', ar: "حارة الفوار", en: 'Harat Al Fawar', district: 'Zgharta' },
  { value: 'Karm Sadeh', ar: "كرم سدّه", en: 'Karm Sadeh', district: 'Zgharta' },
  { value: 'Kfar Sghab', ar: "كفرصغاب", en: 'Kfar Sghab', district: 'Zgharta' },
  { value: 'Kfar Zina', ar: "كفرزينا", en: 'Kfar Zina', district: 'Zgharta' },
  { value: 'Kfardfou', ar: "كفردفو", en: 'Kfardfou', district: 'Zgharta' },
  { value: 'Kfardlakos', ar: "كفردلاقوس", en: 'Kfardlakos', district: 'Zgharta' },
  { value: 'Kfarhata', ar: "كفرحاتا", en: 'Kfarhata', district: 'Zgharta' },
  { value: 'Kfaryachit-Bassbaal', ar: "كفرياشيت - بصبعل", en: 'Kfaryachit-Bassbaal', district: 'Zgharta' },
  { value: 'Majdalia', ar: "مجدليا", en: 'Majdalia', district: 'Zgharta' },
  { value: 'Mazraat Al Tuffah', ar: "مزرعة التفاح", en: 'Mazraat Al Tuffah', district: 'Zgharta' },
  { value: 'Bash Qarah', ar: "باش قره", en: 'Bash Qarah', district: 'Zgharta' },
  { value: 'Rachiine', ar: "رشعين", en: 'Rachiine', district: 'Zgharta' },
  { value: 'Ras Kifa', ar: "راس كيفا", en: 'Ras Kifa', district: 'Zgharta' },
  { value: 'Saraal', ar: "سرعل", en: 'Saraal', district: 'Zgharta' },
  { value: 'Zgharta-Ehden', ar: "زغرتا - إهدن", en: 'Zgharta-Ehden', district: 'Zgharta' },

  // --- Tripoli ---
  { value: 'Al-Badawi', ar: "البداوي", en: 'Al-Badawi', district: 'Tripoli' },
  { value: 'Al-Mina', ar: "الميناء", en: 'Al-Mina', district: 'Tripoli' },
  { value: 'Al-Qalamoun', ar: "القلمون", en: 'Al-Qalamoun', district: 'Tripoli' },
  { value: 'Tripoli', ar: "طرابلس", en: 'Tripoli', district: 'Tripoli' },

  // --- Miniyeh-Danniyeh ---
  { value: 'Aimar', ar: "عيمار", en: 'Aimar', district: 'Miniyeh-Danniyeh' },
  { value: 'Ain Al-Tineh', ar: "عين التينة", en: 'Ain Al-Tineh', district: 'Miniyeh-Danniyeh' },
  { value: 'Al-Hazmiyeh', ar: "الحازمية", en: 'Al-Hazmiyeh', district: 'Miniyeh-Danniyeh' },
  { value: 'Al-Minya', ar: "المنية", en: 'Al-Minya', district: 'Miniyeh-Danniyeh' },
  { value: 'Al-Safira', ar: "السفيرة", en: 'Al-Safira', district: 'Miniyeh-Danniyeh' },
  { value: 'Asoun', ar: "عاصون", en: 'Asoun', district: 'Miniyeh-Danniyeh' },
  { value: 'Bahneen', ar: "بحنين", en: 'Bahneen', district: 'Miniyeh-Danniyeh' },
  { value: 'Bakhoun', ar: "بخعون", en: 'Bakhoun', district: 'Miniyeh-Danniyeh' },
  { value: 'Batarmaz', ar: "بترماز", en: 'Batarmaz', district: 'Miniyeh-Danniyeh' },
  { value: 'Beit Al-Faqas', ar: "بيت الفقس", en: 'Beit Al-Faqas', district: 'Miniyeh-Danniyeh' },
  { value: 'Beqaa Safreen', ar: "بقاع صفرين", en: 'Beqaa Safreen', district: 'Miniyeh-Danniyeh' },
  { value: 'Bshnata', ar: "بشناتا", en: 'Bshnata', district: 'Miniyeh-Danniyeh' },
  { value: 'Bqarsouna', ar: "بقرصونا", en: 'Bqarsouna', district: 'Miniyeh-Danniyeh' },
  { value: 'Burj Al-Yahudiyya', ar: "برج اليهودية", en: 'Burj Al-Yahudiyya', district: 'Miniyeh-Danniyeh' },
  { value: 'Deir Ammar', ar: "دير عمار", en: 'Deir Ammar', district: 'Miniyeh-Danniyeh' },
  { value: 'Deir Nbuhe', ar: "دير نبوح", en: 'Deir Nbuhe', district: 'Miniyeh-Danniyeh' },
  { value: 'Ezaki', ar: "عزقي", en: 'Ezaki', district: 'Miniyeh-Danniyeh' },
  { value: 'Harf Al-Siyad', ar: "حرف السياد", en: 'Harf Al-Siyad', district: 'Miniyeh-Danniyeh' },
  { value: 'Izal', ar: "إزال", en: 'Izal', district: 'Miniyeh-Danniyeh' },
  { value: 'Kfarbanin', ar: "كفربنين", en: 'Kfarbanin', district: 'Miniyeh-Danniyeh' },
  { value: 'Kfarhabu', ar: "كفرحبو", en: 'Kfarhabu', district: 'Miniyeh-Danniyeh' },
  { value: 'Kfarshloun', ar: "كفرشلون", en: 'Kfarshloun', district: 'Miniyeh-Danniyeh' },
  { value: 'Marah Al-Safira', ar: "مرح السفيرة", en: 'Marah Al-Safira', district: 'Miniyeh-Danniyeh' },
  { value: 'Marah Al-Saraj', ar: "مرح السراج", en: 'Marah Al-Saraj', district: 'Miniyeh-Danniyeh' },
  { value: 'Markabta', ar: "مركبتا", en: 'Markabta', district: 'Miniyeh-Danniyeh' },
  { value: 'Bkoza and Namreen', ar: "بقوزا والنمرين", en: 'Bkoza and Namreen', district: 'Miniyeh-Danniyeh' },
  { value: 'Qorsayta', ar: "قرصيتا", en: 'Qorsayta', district: 'Miniyeh-Danniyeh' },
  { value: 'Seer', ar: "سير", en: 'Seer', district: 'Miniyeh-Danniyeh' },
  { value: 'Taran', ar: "طاران", en: 'Taran', district: 'Miniyeh-Danniyeh' },

  // =============================================
  // MOUNT LEBANON
  // =============================================

  // --- Chouf ---
  { value: 'Aalman and Mzaira', ar: "علمان والمزيرعة", en: 'Aalman and Mzaira', district: 'Chouf' },
  { value: 'Ain Ouzain', ar: "عين وزين", en: 'Ain Ouzain', district: 'Chouf' },
  { value: 'Ain Qenye', ar: "عين قنية", en: 'Ain Qenye', district: 'Chouf' },
  { value: 'Ainab', ar: "عيناب", en: 'Ainab (Chouf)', district: 'Chouf' },
  { value: 'Ainout', ar: "عيناب", en: 'Ainout', district: 'Chouf' },
  { value: 'Aitryoun', ar: "عيتريون", en: 'Aitryoun', district: 'Chouf' },
  { value: 'Al Kholouniyeh', ar: "الخلونية", en: 'Al Kholouniyeh', district: 'Chouf' },
  { value: 'Al Khreibeh', ar: "الخريبة", en: 'Al Khreibeh', district: 'Chouf' },
  { value: 'Al Matallah', ar: "المطلة", en: 'Al Matallah', district: 'Chouf' },
  { value: 'Al Mukhtara', ar: "المختارة", en: 'Al Mukhtara', district: 'Chouf' },
  { value: 'Amatour', ar: "عماطور", en: 'Amatour', district: 'Chouf' },
  { value: 'Az-Zuweiriyah', ar: "الزويرية", en: 'Az-Zuweiriyah', district: 'Chouf' },
  { value: 'Baadaran', ar: "بعذران", en: 'Baadaran', district: 'Chouf' },
  { value: 'Baakline', ar: "بعقلين", en: 'Baakline', district: 'Chouf' },
  { value: 'Baassir', ar: "بعاصير", en: 'Baassir', district: 'Chouf' },
  { value: 'Barja', ar: "برجا", en: 'Barja', district: 'Chouf' },
  { value: 'Bassaba', ar: "بصابا", en: 'Bassaba', district: 'Chouf' },
  { value: 'Bater', ar: "باتر", en: 'Bater', district: 'Chouf' },
  { value: 'Bourjein & Mrayjet', ar: "برجين والمريجات", en: 'Bourjein & Mrayjet', district: 'Chouf' },
  { value: 'Btouma', ar: "بتوما", en: 'Btouma', district: 'Chouf' },
  { value: 'Chehim', ar: "شحيم", en: 'Chehim', district: 'Chouf' },
  { value: 'Dahr El-Mghara', ar: "ضهر المغارة", en: 'Dahr El-Mghara', district: 'Chouf' },
  { value: 'Dalhoun', ar: "دلهون", en: 'Dalhoun', district: 'Chouf' },
  { value: 'Daraya', ar: "داريا", en: 'Daraya', district: 'Chouf' },
  { value: 'Gharife', ar: "غريفة", en: 'Gharife', district: 'Chouf' },
  { value: 'Harat Jandal', ar: "حارة جندل", en: 'Harat Jandal', district: 'Chouf' },
  { value: 'Hasrout', ar: "حصروت", en: 'Hasrout', district: 'Chouf' },
  { value: 'Jbaa', ar: "جباع", en: 'Jbaa', district: 'Chouf' },
  { value: 'Jdeideh El Chouf', ar: "الجديدة الشوف", en: 'Jdeideh El Chouf', district: 'Chouf' },
  { value: 'Jedra', ar: "جدرا", en: 'Jedra', district: 'Chouf' },
  { value: 'Jiyeh', ar: "الجية", en: 'Jiyeh', district: 'Chouf' },
  { value: 'Joun', ar: "جون", en: 'Joun', district: 'Chouf' },
  { value: 'Ketermaya', ar: "كترمايا", en: 'Ketermaya', district: 'Chouf' },
  { value: 'Maasser El Chouf', ar: "معاصر الشوف", en: 'Maasser El Chouf', district: 'Chouf' },
  { value: 'Mazboud', ar: "مزبود", en: 'Mazboud', district: 'Chouf' },
  { value: 'Mazraat Ad-Dahr', ar: "مزرعة الضهر", en: 'Mazraat Ad-Dahr', district: 'Chouf' },
  { value: 'Mazraat Ash-Shouf', ar: "مزرعة الشوف", en: 'Mazraat Ash-Shouf', district: 'Chouf' },
  { value: 'Mghayriyeh', ar: "المغيرية", en: 'Mghayriyeh', district: 'Chouf' },
  { value: 'Mristi', ar: "مريستي", en: 'Mristi', district: 'Chouf' },
  { value: 'Niha', ar: "نيحا", en: 'Niha', district: 'Chouf' },
  { value: 'Rmeileh', ar: "الرميلة", en: 'Rmeileh', district: 'Chouf' },
  { value: 'Sibline', ar: "سبلين", en: 'Sibline', district: 'Chouf' },
  { value: 'Smakiah', ar: "سماقية", en: 'Smakiah', district: 'Chouf' },
  { value: 'Wardanieh', ar: "وردانية", en: 'Wardanieh', district: 'Chouf' },

  // --- Keserwan ---
  { value: 'Aaqbiyeh', ar: "عقبية", en: 'Aaqbiyeh', district: 'Keserwan' },
  { value: 'Adma and Al-Dafnah', ar: "أدما والدفنة", en: 'Adma and Al-Dafnah', district: 'Keserwan' },
  { value: 'Ain al-Rehanah', ar: "عين الريحانة", en: 'Ain al-Rehanah', district: 'Keserwan' },
  { value: 'Aintoura', ar: "عينطورة", en: 'Aintoura', district: 'Keserwan' },
  { value: 'Ajaltoun', ar: "عجلتون", en: 'Ajaltoun', district: 'Keserwan' },
  { value: 'Al Bware', ar: "البواري", en: 'Al Bware', district: 'Keserwan' },
  { value: 'Al Hasin', ar: "الحصين", en: 'Al Hasin', district: 'Keserwan' },
  { value: 'Al Qulayat', ar: "القليعات", en: 'Al Qulayat', district: 'Keserwan' },
  { value: 'Al Sahylih', ar: "الساحلية", en: 'Al Sahylih', district: 'Keserwan' },
  { value: 'Al-Azra', ar: "العذراء", en: 'Al-Azra', district: 'Keserwan' },
  { value: 'Al-Ghayneh', ar: "الغينة", en: 'Al-Ghayneh', district: 'Keserwan' },
  { value: 'Aramoun', ar: "عرمون", en: 'Aramoun', district: 'Keserwan' },
  { value: 'Ashqout', ar: "عشقوت", en: 'Ashqout', district: 'Keserwan' },
  { value: 'Batha', ar: "بطحا", en: 'Batha', district: 'Keserwan' },
  { value: 'Bkaatouta', ar: "بقعتوتا", en: 'Bkaatouta', district: 'Keserwan' },
  { value: 'Blouneh', ar: "بلونة", en: 'Blouneh', district: 'Keserwan' },
  { value: 'Bzommar', ar: "بزمار", en: 'Bzommar', district: 'Keserwan' },
  { value: 'Chehatoal', ar: "شحتول", en: 'Chehatoal', district: 'Keserwan' },
  { value: 'Dalbatta', ar: "دلبتا", en: 'Dalbatta', district: 'Keserwan' },
  { value: 'Daroun', ar: "درعون", en: 'Daroun', district: 'Keserwan' },
  { value: 'Darya', ar: "دارية", en: 'Darya', district: 'Keserwan' },
  { value: 'DoukMakayl', ar: "دوك ميخائيل", en: 'DoukMakayl', district: 'Keserwan' },
  { value: 'Faitroun', ar: "فيطرون", en: 'Faitroun', district: 'Keserwan' },
  { value: 'Faraya', ar: "فاريا", en: 'Faraya', district: 'Keserwan' },
  { value: 'Fatqa', ar: "فتقا", en: 'Fatqa', district: 'Keserwan' },
  { value: 'Ghabaleh', ar: "غباله", en: 'Ghabaleh', district: 'Keserwan' },
  { value: 'Ghazir', ar: "غزير", en: 'Ghazir', district: 'Keserwan' },
  { value: 'Ghodras', ar: "غدراس", en: 'Ghodras', district: 'Keserwan' },
  { value: 'Ghousta', ar: "غوسطا", en: 'Ghousta', district: 'Keserwan' },
  { value: 'Harajel', ar: "حراجل", en: 'Harajel', district: 'Keserwan' },
  { value: 'Haytah', ar: "هيتا", en: 'Haytah', district: 'Keserwan' },
  { value: 'Jdeideh', ar: "الجديدة", en: 'Jdeideh', district: 'Keserwan' },
  { value: 'Joueita', ar: "جويتة", en: 'Joueita', district: 'Keserwan' },
  { value: 'Jounieh', ar: "جونية", en: 'Jounieh', district: 'Keserwan' },
  { value: 'Jourat Al Terms', ar: "جورة الترمس", en: 'Jourat Al Terms', district: 'Keserwan' },
  { value: 'Jourat Badran', ar: "جورة بدران", en: 'Jourat Badran', district: 'Keserwan' },
  { value: 'Kfardbian', ar: "كفردبيان", en: 'Kfardbian', district: 'Keserwan' },
  { value: 'Kfertay', ar: "كفرتيه", en: 'Kfertay', district: 'Keserwan' },
  { value: 'Kfouar', ar: "كفور", en: 'Kfouar', district: 'Keserwan' },
  { value: 'Maissara', ar: "ميسرة", en: 'Maissara', district: 'Keserwan' },
  { value: 'Merouba', ar: "ميروبا", en: 'Merouba', district: 'Keserwan' },
  { value: 'Nemoura & Kfar Jarif', ar: "نموره وكفرجريف", en: 'Nemoura & Kfar Jarif', district: 'Keserwan' },
  { value: 'Rachin', ar: "رشين", en: 'Rachin', district: 'Keserwan' },
  { value: 'Reefoun', ar: "ريفون", en: 'Reefoun', district: 'Keserwan' },
  { value: 'Safra', ar: "صفرا", en: 'Safra', district: 'Keserwan' },
  { value: 'Shennaya', ar: "شننعير", en: 'Shennaya', district: 'Keserwan' },
  { value: 'Tabarja', ar: "طبرجا", en: 'Tabarja', district: 'Keserwan' },
  { value: 'Wata Al Joz', ar: "وطى الجوز", en: 'Wata Al Joz', district: 'Keserwan' },
  { value: 'Yahchouch', ar: "يحشوش", en: 'Yahchouch', district: 'Keserwan' },
  { value: 'Zaaitra', ar: "زعيترة", en: 'Zaaitra', district: 'Keserwan' },
  { value: 'Zaytoun', ar: "الزيتون", en: 'Zaytoun', district: 'Keserwan' },
  { value: 'Zouk Mosbeh', ar: "ذوق مصبح", en: 'Zouk Mosbeh', district: 'Keserwan' },

  // --- Metn ---
  { value: 'Aeroun', ar: "عيرون", en: 'Aeroun', district: 'Metn' },
  { value: 'Ain Saadeh', ar: "عين سعادة", en: 'Ain Saadeh', district: 'Metn' },
  { value: 'Al Ghabbah', ar: "الغابة", en: 'Al Ghabbah', district: 'Metn' },
  { value: 'Al Jadeeda - Al Boushriyeh', ar: "الجديدة - البوشرية", en: 'Al Jadeeda - Al Boushriyeh', district: 'Metn' },
  { value: 'Al Mansouriyah', ar: "المنصورية", en: 'Al Mansouriyah', district: 'Metn' },
  { value: 'Al Oyoun', ar: "العيون", en: 'Al Oyoun', district: 'Metn' },
  { value: 'Antelias', ar: "أنطلياس", en: 'Antelias', district: 'Metn' },
  { value: 'Baabdat', ar: "بعبدات", en: 'Baabdat', district: 'Metn' },
  { value: 'Batgrine', ar: "بتغرين", en: 'Batgrine', district: 'Metn' },
  { value: 'Beit Chabab', ar: "بيت شباب", en: 'Beit Chabab', district: 'Metn' },
  { value: 'Beit Chaar', ar: "بيت شعار", en: 'Beit Chaar', district: 'Metn' },
  { value: 'Beit Meri', ar: "بيت مري", en: 'Beit Meri', district: 'Metn' },
  { value: 'Bikfaya', ar: "بكفيا", en: 'Bikfaya', district: 'Metn' },
  { value: 'Bourj Hammoud', ar: "برج حمود", en: 'Bourj Hammoud', district: 'Metn' },
  { value: 'Broumana', ar: "برمانا", en: 'Broumana', district: 'Metn' },
  { value: 'Bsallim', ar: "بصاليم", en: 'Bsallim', district: 'Metn' },
  { value: 'Byakout', ar: "بياقوت", en: 'Byakout', district: 'Metn' },
  { value: 'Dahr El Sawan', ar: "ضهر الصوان", en: 'Dahr El Sawan', district: 'Metn' },
  { value: 'Dawwar', ar: "ضوار", en: 'Dawwar', district: 'Metn' },
  { value: 'Dbayeh', ar: "ضبية", en: 'Dbayeh', district: 'Metn' },
  { value: 'Dekwaneh', ar: "الدكوانة", en: 'Dekwaneh', district: 'Metn' },
  { value: 'Fanar', ar: "الفنار", en: 'Fanar', district: 'Metn' },
  { value: 'Jal El Dib', ar: "جل الديب", en: 'Jal El Dib', district: 'Metn' },
  { value: 'Mar Chaaya', ar: "مار شعيا", en: 'Mar Chaaya', district: 'Metn' },
  { value: 'Mar Musa', ar: "مار موسى", en: 'Mar Musa', district: 'Metn' },
  { value: 'Mazraat Yashouh', ar: "مزرعة يشوع", en: 'Mazraat Yashouh', district: 'Metn' },
  { value: 'Nabiheet', ar: "نابيهيت", en: 'Nabiheet', district: 'Metn' },
  { value: 'Qanabah Baramana', ar: "قنابة برمانا", en: 'Qanabah Baramana', district: 'Metn' },
  { value: 'Qornet Chehwan', ar: "قرنة شهوان", en: 'Qornet Chehwan', district: 'Metn' },
  { value: 'Rabieh', ar: "الرابية", en: 'Rabieh', district: 'Metn' },
  { value: 'Roumiyeh', ar: "الرومية", en: 'Roumiyeh', district: 'Metn' },
  { value: 'Saqiyat Al-Misk', ar: "ساقية المسك", en: 'Saqiyat Al-Misk', district: 'Metn' },
  { value: 'Sin El Fil', ar: "سن الفيل", en: 'Sin El Fil', district: 'Metn' },
  { value: 'Zalka', ar: "الزلقا", en: 'Zalka', district: 'Metn' },

  // --- Baabda ---
  { value: 'Al Kalaa', ar: "القلعة", en: 'Al Kalaa', district: 'Baabda' },
  { value: 'Al Karya', ar: "القرية", en: 'Al Karya', district: 'Baabda' },
  { value: 'Al-Kosiba', ar: "القصيبة", en: 'Al-Kosiba', district: 'Baabda' },
  { value: 'Al-Muraijeh-Tahweta', ar: "المريجة - التحويطة", en: 'Al-Muraijeh-Tahweta', district: 'Baabda' },
  { value: 'Al-Urbaniyah-Al-Dalibah', ar: "العربانية - الدليبة", en: 'Al-Urbaniyah-Al-Dalibah', district: 'Baabda' },
  { value: 'Arayya', ar: "عاريا", en: 'Arayya', district: 'Baabda' },
  { value: 'Arsoun', ar: "عرسون", en: 'Arsoun', district: 'Baabda' },
  { value: 'Bmariam', ar: "بمريم", en: 'Bmariam', district: 'Baabda' },
  { value: 'Btekhniyeh', ar: "بتخنيه", en: 'Btekhniyeh', district: 'Baabda' },
  { value: 'Burj al-Barajneh', ar: "برج البراجنة", en: 'Burj al-Barajneh', district: 'Baabda' },
  { value: 'Bzebdine', ar: "بزبدين", en: 'Bzebdine', district: 'Baabda' },
  { value: 'Chiyah', ar: "الشياح", en: 'Chiyah', district: 'Baabda' },
  { value: 'Deir El Harf', ar: "دير الحرف", en: 'Deir El Harf', district: 'Baabda' },
  { value: 'Furn El Chebbak', ar: "فرن الشباك", en: 'Furn El Chebbak', district: 'Baabda' },
  { value: 'Ghobeiry', ar: "الغبيري", en: 'Ghobeiry', district: 'Baabda' },
  { value: 'Hammana', ar: "حمانا", en: 'Hammana', district: 'Baabda' },
  { value: 'Haret Hreik', ar: "حارة حريك", en: 'Haret Hreik', district: 'Baabda' },
  { value: 'Hasbaya (Baabda)', ar: "حصبيا (بعبدا)", en: 'Hasbaya (Baabda)', district: 'Baabda' },
  { value: 'Hazmieh', ar: "الحازمية", en: 'Hazmieh', district: 'Baabda' },
  { value: 'Hilalia', ar: "هلالية", en: 'Hilalia', district: 'Baabda' },
  { value: 'Jewar Al Haouz', ar: "جوار الحوز", en: 'Jewar Al Haouz', district: 'Baabda' },
  { value: 'Jouret Arsoun', ar: "جورة عرسون", en: 'Jouret Arsoun', district: 'Baabda' },
  { value: 'Kfarselwan', ar: "كفرسلوان", en: 'Kfarselwan', district: 'Baabda' },
  { value: 'Khuraibeh', ar: "الخريبة", en: 'Khuraibeh', district: 'Baabda' },
  { value: 'Qabi', ar: "قبي", en: 'Qabi', district: 'Baabda' },
  { value: 'Qornayel', ar: "قرنايل", en: 'Qornayel', district: 'Baabda' },
  { value: 'Qortada', ar: "قرطاضة", en: 'Qortada', district: 'Baabda' },
  { value: 'Ras Al Harf', ar: "راس الحرف", en: 'Ras Al Harf', district: 'Baabda' },
  { value: 'Ras al-Matn', ar: "راس المتن", en: 'Ras al-Matn', district: 'Baabda' },
  { value: 'Ruwayset El Ballout', ar: "رويسة البلوط", en: 'Ruwayset El Ballout', district: 'Baabda' },
  { value: 'Salima', ar: "سليمة", en: 'Salima', district: 'Baabda' },
  { value: 'Shabaniya', ar: "الشبانية", en: 'Shabaniya', district: 'Baabda' },
  { value: 'Shuwit', ar: "شويت", en: 'Shuwit', district: 'Baabda' },
  { value: 'Tarshish', ar: "ترشيش", en: 'Tarshish', district: 'Baabda' },

  // --- Aley ---
  { value: 'Ainab (Aley)', ar: "عيناب (عاليه)", en: 'Ainab (Aley)', district: 'Aley' },
  { value: 'Al Bneyeh', ar: "البنية", en: 'Al Bneyeh', district: 'Aley' },
  { value: 'Al Bsatin', ar: "البساتين", en: 'Al Bsatin', district: 'Aley' },
  { value: 'Al Mansouriya', ar: "المنصورية", en: 'Al Mansouriya', district: 'Aley' },
  { value: 'Al Mashrefah', ar: "المشرفة", en: 'Al Mashrefah', district: 'Aley' },
  { value: 'Batater', ar: "بطاطر", en: 'Batater', district: 'Aley' },
  { value: 'Baysour', ar: "بيصور", en: 'Baysour', district: 'Aley' },
  { value: 'Bdeghan', ar: "بدغان", en: 'Bdeghan', district: 'Aley' },
  { value: 'Bhamdoun', ar: "بحمدون", en: 'Bhamdoun', district: 'Aley' },
  { value: 'Chanehye', ar: "شانيه", en: 'Chanehye', district: 'Aley' },
  { value: 'Charoun', ar: "شارون", en: 'Charoun', district: 'Aley' },
  { value: 'Dfoun', ar: "دفون", en: 'Dfoun', district: 'Aley' },
  { value: 'Kaifun', ar: "كيفون", en: 'Kaifun', district: 'Aley' },
  { value: 'Kfarmatta', ar: "كفرمتى", en: 'Kfarmatta', district: 'Aley' },
  { value: 'Majdlaya', ar: "مجدليا", en: 'Majdlaya', district: 'Aley' },
  { value: 'Remhala', ar: "رمحالا", en: 'Remhala', district: 'Aley' },
  { value: 'Sofar', ar: "صوفر", en: 'Sofar', district: 'Aley' },

  // --- Jbeil (Byblos) ---
  { value: 'Ahmouch', ar: "أحمج", en: 'Ahmouch', district: 'Jbeil' },
  { value: 'Ain Al Gowayba', ar: "عين الغويبة", en: 'Ain Al Gowayba', district: 'Jbeil' },
  { value: 'Al Aqoura', ar: "العاقورة", en: 'Al Aqoura', district: 'Jbeil' },
  { value: 'Al Mansaf', ar: "المنصف", en: 'Al Mansaf', district: 'Jbeil' },
  { value: 'Amshit', ar: "عمشيت", en: 'Amshit', district: 'Jbeil' },
  { value: 'Fatri', ar: "فاتري", en: 'Fatri', district: 'Jbeil' },
  { value: 'Halat', ar: "حالات", en: 'Halat', district: 'Jbeil' },
  { value: 'Jaj', ar: "جاج", en: 'Jaj', district: 'Jbeil' },
  { value: 'Jbeil', ar: "جبيل", en: 'Jbeil', district: 'Jbeil' },
  { value: 'Lassa', ar: "لاسا", en: 'Lassa', district: 'Jbeil' },
  { value: 'Mifouk', ar: "ميفوق", en: 'Mifouk', district: 'Jbeil' },
  { value: 'Nahr Ibrahim', ar: "نهر إبراهيم", en: 'Nahr Ibrahim', district: 'Jbeil' },
  { value: 'Qartaba', ar: "قرطبا", en: 'Qartaba', district: 'Jbeil' },
  { value: 'Tartij', ar: "تارتيج", en: 'Tartij', district: 'Jbeil' },

  // =============================================
  // AKKAR
  // =============================================

  // --- Akkar ---
  { value: 'Ad Daghlah', ar: "الدغلة", en: 'Ad Daghlah', district: 'Akkar' },
  { value: 'Aidmoon-Shekhlar', ar: "عيدمون - شيخلار", en: 'Aidmoon-Shekhlar', district: 'Akkar' },
  { value: 'Ain al-Dhahab', ar: "عين الذهب", en: 'Ain al-Dhahab', district: 'Akkar' },
  { value: 'Ain al-Zayt', ar: "عين الزيت", en: 'Ain al-Zayt', district: 'Akkar' },
  { value: 'Ain Yaaqub', ar: "عين يعقوب", en: 'Ain Yaaqub', district: 'Akkar' },
  { value: 'Akkar el-Atiqa', ar: "عكار العتيقة", en: 'Akkar el-Atiqa', district: 'Akkar' },
  { value: 'Akroum', ar: "عكروم", en: 'Akroum', district: 'Akkar' },
  { value: 'Al Aamair', ar: "العمائر", en: 'Al Aamair', district: 'Akkar' },
  { value: 'Al Aboudiyeh', ar: "العبودية", en: 'Al Aboudiyeh', district: 'Akkar' },
  { value: 'Al Awainat', ar: "العوينات", en: 'Al Awainat', district: 'Akkar' },
  { value: 'Al Bireh', ar: "البيرة", en: 'Al Bireh', district: 'Akkar' },
  { value: 'Al Burj', ar: "البرج", en: 'Al Burj', district: 'Akkar' },
  { value: 'Al Farid', ar: "الفريدة", en: 'Al Farid', district: 'Akkar' },
  { value: 'Al Hakour', ar: "الحاكور", en: 'Al Hakour', district: 'Akkar' },
  { value: 'Al Hishah', ar: "الحيشة", en: 'Al Hishah', district: 'Akkar' },
  { value: 'Al Hissa', ar: "الحصة", en: 'Al Hissa', district: 'Akkar' },
  { value: 'Al Hmayra', ar: "الحميرة", en: 'Al Hmayra', district: 'Akkar' },
  { value: 'Al Kweikhat', ar: "الكويخات", en: 'Al Kweikhat', district: 'Akkar' },
  { value: 'Al Majdal', ar: "المجدل", en: 'Al Majdal', district: 'Akkar' },
  { value: 'Al Maqybleh', ar: "المقيبلة", en: 'Al Maqybleh', district: 'Akkar' },
  { value: 'Al Qariyat', ar: "القريات", en: 'Al Qariyat', district: 'Akkar' },
  { value: 'Al Qobeiyat', ar: "القبيات", en: 'Al Qobeiyat', district: 'Akkar' },
  { value: 'Al Qurnah', ar: "القرنة", en: 'Al Qurnah', district: 'Akkar' },
  { value: 'Al Talil', ar: "التليل", en: 'Al Talil', district: 'Akkar' },
  { value: 'Al-Ayoun', ar: "العيون", en: 'Al-Ayoun', district: 'Akkar' },
  { value: 'Al-Dabbabiya', ar: "الدبابية", en: 'Al-Dabbabiya', district: 'Akkar' },
  { value: 'Al-Kwashra', ar: "الكواشرة", en: 'Al-Kwashra', district: 'Akkar' },
  { value: 'Al-Mahmara', ar: "المحمرة", en: 'Al-Mahmara', district: 'Akkar' },
  { value: 'Al-Maqeeta', ar: "المقيطع", en: 'Al-Maqeeta', district: 'Akkar' },
  { value: 'Al-Mounasseh', ar: "المنسة", en: 'Al-Mounasseh', district: 'Akkar' },
  { value: 'Al-Qantara', ar: "القنطرة", en: 'Al-Qantara', district: 'Akkar' },
  { value: 'Al-Qarqaf', ar: "القرقف", en: 'Al-Qarqaf', district: 'Akkar' },
  { value: 'Al-Rihaneya', ar: "الريحانية", en: 'Al-Rihaneya', district: 'Akkar' },
  { value: 'Al-Sheikh Ayyash', ar: "الشيخ عياش", en: 'Al-Sheikh Ayyash', district: 'Akkar' },
  { value: 'Ammar Al-Beykat', ar: "عمار البيكات", en: 'Ammar Al-Beykat', district: 'Akkar' },
  { value: 'An Nafiseh', ar: "النفيسة", en: 'An Nafiseh', district: 'Akkar' },
  { value: 'An Naheriyah', ar: "النهرية", en: 'An Naheriyah', district: 'Akkar' },
  { value: 'Andqet', ar: "عندقت", en: 'Andqet', district: 'Akkar' },
  { value: 'Arqa', ar: "عرقا", en: 'Arqa', district: 'Akkar' },
  { value: 'As Sulah', ar: "السلة", en: 'As Sulah', district: 'Akkar' },
  { value: 'Ash Shuqduf', ar: "الشقدوف", en: 'Ash Shuqduf', district: 'Akkar' },
  { value: 'Ayun al-Ghazlan', ar: "عيون الغزلان", en: 'Ayun al-Ghazlan', district: 'Akkar' },
  { value: 'Ayyat', ar: "عيات", en: 'Ayyat', district: 'Akkar' },
  { value: 'Bani Sakhr', ar: "بني صخر", en: 'Bani Sakhr', district: 'Akkar' },
  { value: 'Barbarah', ar: "بربارة", en: 'Barbarah', district: 'Akkar' },
  { value: 'Barkaayl', ar: "بركايل", en: 'Barkaayl', district: 'Akkar' },
  { value: 'Bayno - Qaboula', ar: "بينو - قبولا", en: 'Bayno - Qaboula', district: 'Akkar' },
  { value: 'Bayt Ayyub', ar: "بيت أيوب", en: 'Bayt Ayyub', district: 'Akkar' },
  { value: 'Bayt Mlat', ar: "بيت ملات", en: 'Bayt Mlat', district: 'Akkar' },
  { value: 'Bazal', ar: "بزال", en: 'Bazal', district: 'Akkar' },
  { value: 'Bazbina', ar: "بزبينا", en: 'Bazbina', district: 'Akkar' },
  { value: 'Bebnine', ar: "ببنين", en: 'Bebnine', district: 'Akkar' },
  { value: 'Beit El Hajj', ar: "بيت الحاج", en: 'Beit El Hajj', district: 'Akkar' },
  { value: 'Beit Younes', ar: "بيت يونس", en: 'Beit Younes', district: 'Akkar' },
  { value: 'Biqrazla', ar: "بقرزلا", en: 'Biqrazla', district: 'Akkar' },
  { value: 'Burj Al Arab', ar: "برج العرب", en: 'Burj Al Arab', district: 'Akkar' },
  { value: 'Dahr Qanbar', ar: "ضهر قنبر", en: 'Dahr Qanbar', district: 'Akkar' },
  { value: 'Dahr Laysina', ar: "ضهر ليسينا", en: 'Dahr Laysina', district: 'Akkar' },
  { value: 'Deir Dalloum', ar: "دير دلوم", en: 'Deir Dalloum', district: 'Akkar' },
  { value: 'Deir Janine', ar: "دير جنين", en: 'Deir Janine', district: 'Akkar' },
  { value: 'Dura', ar: "دورا", en: 'Dura', district: 'Akkar' },
  { value: 'Dusa and Baghdad', ar: "دوسا وبغداد", en: 'Dusa and Baghdad', district: 'Akkar' },
  { value: 'Dweir Adwiya', ar: "دوير عدوية", en: 'Dweir Adwiya', district: 'Akkar' },
  { value: 'Eilat', ar: "إيلات", en: 'Eilat', district: 'Akkar' },
  { value: 'Fassikin', ar: "فسيكين", en: 'Fassikin', district: 'Akkar' },
  { value: 'Fnaideq', ar: "فنيدق", en: 'Fnaideq', district: 'Akkar' },
  { value: 'Ghazilah', ar: "غزيلة", en: 'Ghazilah', district: 'Akkar' },
  { value: 'Halba', ar: "حلبا", en: 'Halba', district: 'Akkar' },
  { value: 'Harrar', ar: "حرار", en: 'Harrar', district: 'Akkar' },
  { value: 'Haytla', ar: "هيطلا", en: 'Haytla', district: 'Akkar' },
  { value: 'Hayzouq', ar: "حيزوق", en: 'Hayzouq', district: 'Akkar' },
  { value: 'Houbesh', ar: "حوبيش", en: 'Houbesh', district: 'Akkar' },
  { value: 'Jarmnaya and Ar Rama', ar: "جرمنايا والرامة", en: 'Jarmnaya and Ar Rama', district: 'Akkar' },
  { value: 'Jdeideh Al Juma', ar: "الجديدة الجمعة", en: 'Jdeideh Al Juma', district: 'Akkar' },
  { value: 'Jdeideh Al Qaytaa', ar: "الجديدة القيطع", en: 'Jdeideh Al Qaytaa', district: 'Akkar' },
  { value: 'Jebrayel', ar: "جبرايل", en: 'Jebrayel', district: 'Akkar' },
  { value: 'Karm Aassfour', ar: "كرم عصفور", en: 'Karm Aassfour', district: 'Akkar' },
  { value: 'Kfarton', ar: "كفرتون", en: 'Kfarton', district: 'Akkar' },
  { value: 'Kharba Shar', ar: "خربا شار", en: 'Kharba Shar', district: 'Akkar' },
  { value: 'Kharbit Dawud', ar: "خربة داود", en: 'Kharbit Dawud', district: 'Akkar' },
  { value: 'Khat al Petrol', ar: "خط البترول", en: 'Khat al Petrol', district: 'Akkar' },
  { value: 'Khuraibeh (Akkar)', ar: "الخريبة (عكار)", en: 'Khuraibeh', district: 'Akkar' },
  { value: 'Kousha', ar: "كوشا", en: 'Kousha', district: 'Akkar' },
  { value: 'Kroom Arab', ar: "كروم عرب", en: 'Kroom Arab', district: 'Akkar' },
  { value: 'Majdala', ar: "مجدلا", en: 'Majdala', district: 'Akkar' },
  { value: 'Mamna', ar: "ممنع", en: 'Mamna', district: 'Akkar' },
  { value: 'Mar Touma', ar: "مار توما", en: 'Mar Touma', district: 'Akkar' },
  { value: 'Mashha', ar: "مشحا", en: 'Mashha', district: 'Akkar' },
  { value: 'Mazraat Bleda', ar: "مزرعة بلدا", en: 'Mazraat Bleda', district: 'Akkar' },
  { value: 'Minyara', ar: "منيارة", en: 'Minyara', district: 'Akkar' },
  { value: 'Mishmish', ar: "مشمش", en: 'Mishmish', district: 'Akkar' },
  { value: 'Munjaz', ar: "منجز", en: 'Munjaz', district: 'Akkar' },
  { value: 'Mushta Hamoud', ar: "مشتى حمود", en: 'Mushta Hamoud', district: 'Akkar' },
  { value: 'Nurah', ar: "نورا", en: 'Nurah', district: 'Akkar' },
  { value: 'Qaliyat', ar: "القليعات", en: 'Qaliyat', district: 'Akkar' },
  { value: 'Qoubbet Chamra - Semqley', ar: "قبة شمرا - سمقلية", en: 'Qoubbet Chamra - Semqley', district: 'Akkar' },
  { value: 'Qubayyat', ar: "القبيات", en: 'Qubayyat', district: 'Akkar' },
  { value: 'Quneya', ar: "قنية", en: 'Quneya', district: 'Akkar' },
  { value: 'Rahba', ar: "رحبا", en: 'Rahba', district: 'Akkar' },
  { value: 'Rimah', ar: "رماح", en: 'Rimah', district: 'Akkar' },
  { value: 'Safinat Al-Qetaa', ar: "سفينة القيطع", en: 'Safinat Al-Qetaa', district: 'Akkar' },
  { value: 'Safinet al-Dreib', ar: "سفينة الضريب", en: 'Safinet al-Dreib', district: 'Akkar' },
  { value: 'Sandiyaneh Raydan', ar: "صندانية ريدان", en: 'Sandiyaneh Raydan', district: 'Akkar' },
  { value: 'Shan', ar: "شعن", en: 'Shan', district: 'Akkar' },
  { value: 'Sharbila', ar: "شربيلا", en: 'Sharbila', district: 'Akkar' },
  { value: 'Sheikh Mohammad - Aadbal', ar: "الشيخ محمد - عدبل", en: 'Sheikh Mohammad - Aadbal', district: 'Akkar' },
  { value: 'Sheikh Taba', ar: "الشيخ طابا", en: 'Sheikh Taba', district: 'Akkar' },
  { value: 'Shiddreh', ar: "شدرا", en: 'Shiddreh', district: 'Akkar' },
  { value: 'Sissouk', ar: "سيسوق", en: 'Sissouk', district: 'Akkar' },
  { value: 'Swayseh', ar: "سويسة", en: 'Swayseh', district: 'Akkar' },
  { value: 'Takrit', ar: "تكريت", en: 'Takrit', district: 'Akkar' },
  { value: 'Tal Abbas Al Gharbi', ar: "تل عباس الغربي", en: 'Tal Abbas Al Gharbi', district: 'Akkar' },
  { value: 'Talla Washataha', ar: "تلة وشتاها", en: 'Talla Washataha', district: 'Akkar' },
  { value: 'Talmaayan', ar: "تلمعيان", en: 'Talmaayan', district: 'Akkar' },
  { value: 'Tasha', ar: "طاشع", en: 'Tasha', district: 'Akkar' },
  { value: 'Wadi Al-Hawr', ar: "وادي الحور", en: 'Wadi Al-Hawr', district: 'Akkar' },
  { value: 'Wadi al-Jamus', ar: "وادي الجاموس", en: 'Wadi al-Jamus', district: 'Akkar' },
  { value: 'Wadi Khalid', ar: "وادي خالد", en: 'Wadi Khalid', district: 'Akkar' },
  { value: 'Zawarib', ar: "زوارب", en: 'Zawarib', district: 'Akkar' },
  { value: 'Zouk al-Hssayne', ar: "ذوق الحصين", en: 'Zouk al-Hssayne', district: 'Akkar' },
  { value: 'Zouk Hadara', ar: "ذوق حدارا", en: 'Zouk Hadara', district: 'Akkar' },

  // =============================================
  // SOUTH LEBANON
  // =============================================

  // --- Sidon ---
  { value: 'Aabra', ar: "عبرا", en: 'Aabra', district: 'Sidon' },
  { value: 'Adloun', ar: "عدلون", en: 'Adloun', district: 'Sidon' },
  { value: 'Adousiyeh', ar: "العدوسية", en: 'Adousiyeh', district: 'Sidon' },
  { value: 'Ain Eddelb', ar: "عين الدلب", en: 'Ain Eddelb', district: 'Sidon' },
  { value: 'Al Bisariyah', ar: "البصارية", en: 'Al Bisariyah', district: 'Sidon' },
  { value: 'Al Hilaliyah', ar: "الهلالية", en: 'Al Hilaliyah', district: 'Sidon' },
  { value: 'Al Lubiyah', ar: "اللوبية", en: 'Al Lubiyah', district: 'Sidon' },
  { value: 'Al Marwaniyah', ar: "المروانية", en: 'Al Marwaniyah', district: 'Sidon' },
  { value: 'Al Mayy Wal Mayy', ar: "الميّ والميّ", en: 'Al Mayy Wal Mayy', district: 'Sidon' },
  { value: 'Al Quryah', ar: "القرية", en: 'Al Quryah', district: 'Sidon' },
  { value: 'An Najariyah', ar: "النجارية", en: 'An Najariyah', district: 'Sidon' },
  { value: 'Anqoun', ar: "عنقون", en: 'Anqoun', district: 'Sidon' },
  { value: 'Ansariyah', ar: "الأنصارية", en: 'Ansariyah', district: 'Sidon' },
  { value: 'Babliyeh', ar: "البابلية", en: 'Babliyeh', district: 'Sidon' },
  { value: 'Baksata', ar: "بقسطا", en: 'Baksata', district: 'Sidon' },
  { value: 'Baramiyeh', ar: "البرامية", en: 'Baramiyeh', district: 'Sidon' },
  { value: 'Derb Essim', ar: "درب السيم", en: 'Derb Essim', district: 'Sidon' },
  { value: 'Ghassaniyeh', ar: "الغسانية", en: 'Ghassaniyeh', district: 'Sidon' },
  { value: 'Ghazieh', ar: "الغازية", en: 'Ghazieh', district: 'Sidon' },
  { value: 'Haret Saida', ar: "حارة صيدا", en: 'Haret Saida', district: 'Sidon' },
  { value: 'Kawthariyat al-Siyad', ar: "كوثرية السياد", en: 'Kawthariyat al-Siyad', district: 'Sidon' },
  { value: 'Khartoum', ar: "الخرطوم", en: 'Khartoum', district: 'Sidon' },
  { value: 'Majdalyoun', ar: "مجدليون", en: 'Majdalyoun', district: 'Sidon' },
  { value: 'Mghdousheh', ar: "مغدوشة", en: 'Mghdousheh', district: 'Sidon' },
  { value: 'Qaqaiyyat al-Sanawbar', ar: "قعقعية الصنوبر", en: 'Qaqaiyyat al-Sanawbar', district: 'Sidon' },
  { value: 'Saksakiye', ar: "صكسكية", en: 'Saksakiye', district: 'Sidon' },
  { value: 'Salehieh', ar: "الصالحية", en: 'Salehieh', district: 'Sidon' },
  { value: 'Sarafand', ar: "الصرفند", en: 'Sarafand', district: 'Sidon' },
  { value: 'Sidon', ar: "صيدا", en: 'Sidon', district: 'Sidon' },
  { value: 'Taffahita', ar: "التفاحتا", en: 'Taffahita', district: 'Sidon' },
  { value: 'Tanbourit', ar: "تنبوريت", en: 'Tanbourit', district: 'Sidon' },

  // --- Tyre ---
  { value: 'Ain Baal', ar: "عين بعال", en: 'Ain Baal', district: 'Tyre' },
  { value: 'Al Abbasiyah', ar: "العباسية", en: 'Al Abbasiyah', district: 'Tyre' },
  { value: 'Al Bayyad', ar: "البياض", en: 'Al Bayyad', district: 'Tyre' },
  { value: 'Al Bazuriyah', ar: "البازورية", en: 'Al Bazuriyah', district: 'Tyre' },
  { value: 'Al Burghliye', ar: "البرغلية", en: 'Al Burghliye', district: 'Tyre' },
  { value: 'Al Bustan', ar: "البستان", en: 'Al Bustan', district: 'Tyre' },
  { value: 'Al Hamiri', ar: "الحميري", en: 'Al Hamiri', district: 'Tyre' },
  { value: 'Al Hlousiyeh', ar: "الحلوسية", en: 'Al Hlousiyeh', district: 'Tyre' },
  { value: 'Al Jibbin', ar: "الجبين", en: 'Al Jibbin', district: 'Tyre' },
  { value: 'Al Mansouri', ar: "المنصوري", en: 'Al Mansouri', district: 'Tyre' },
  { value: 'Al Qulaylah', ar: "القليلة", en: 'Al Qulaylah', district: 'Tyre' },
  { value: 'Al Shaatiye', ar: "الشاطئية", en: 'Al Shaatiye', district: 'Tyre' },
  { value: 'Alhinya', ar: "الهنية", en: 'Alhinya', district: 'Tyre' },
  { value: 'Alkanisa', ar: "الكنيسة", en: 'Alkanisa', district: 'Tyre' },
  { value: 'Alma Ash Shaaab', ar: "علما الشعب", en: 'Alma Ash Shaaab', district: 'Tyre' },
  { value: 'Alzahira', ar: "الظهيرة", en: 'Alzahira', district: 'Tyre' },
  { value: 'An Naqoura', ar: "الناقورة", en: 'An Naqoura', district: 'Tyre' },
  { value: 'Arzoun', ar: "أرزون", en: 'Arzoun', district: 'Tyre' },
  { value: 'Aytit', ar: "عيتيت", en: 'Aytit', district: 'Tyre' },
  { value: 'Batoulieh', ar: "البتولية", en: 'Batoulieh', district: 'Tyre' },
  { value: 'Bedeas', ar: "بدياس", en: 'Bedeas', district: 'Tyre' },
  { value: 'Bourj Al Shamali', ar: "برج الشمالي", en: 'Bourj Al Shamali', district: 'Tyre' },
  { value: 'Bourj Rahhal', ar: "برج رحال", en: 'Bourj Rahhal', district: 'Tyre' },
  { value: 'Deir Amess', ar: "دير عامص", en: 'Deir Amess', district: 'Tyre' },
  { value: 'Deir Keifa', ar: "دير كيفا", en: 'Deir Keifa', district: 'Tyre' },
  { value: 'Deir Qanoun En Nahr', ar: "دير قانون النهر", en: 'Deir Qanoun En Nahr', district: 'Tyre' },
  { value: 'Deir Qanoun Ras Al Ain', ar: "دير قانون راس العين", en: 'Deir Qanoun Ras Al Ain', district: 'Tyre' },
  { value: 'Dirdghayya', ar: "دردغيا", en: 'Dirdghayya', district: 'Tyre' },
  { value: 'Hinawiye', ar: "حناوية", en: 'Hinawiye', district: 'Tyre' },
  { value: 'Jabal Albutm', ar: "جبل البطم", en: 'Jabal Albutm', district: 'Tyre' },
  { value: 'Jannata', ar: "جناتا", en: 'Jannata', district: 'Tyre' },
  { value: 'Maaroub', ar: "معروب", en: 'Maaroub', district: 'Tyre' },
  { value: 'Majadel', ar: "مجادل", en: 'Majadel', district: 'Tyre' },
  { value: 'Majdalzoun', ar: "مجدلزون", en: 'Majdalzoun', district: 'Tyre' },
  { value: 'Marwahine', ar: "مروحين", en: 'Marwahine', district: 'Tyre' },
  { value: 'Mazraat Moshref', ar: "مزرعة مشرف", en: 'Mazraat Moshref', district: 'Tyre' },
  { value: 'Mearka', ar: "معركة", en: 'Mearka', district: 'Tyre' },
  { value: 'Qana', ar: "قانا", en: 'Qana', district: 'Tyre' },
  { value: 'Ramadiyeh', ar: "الرمادية", en: 'Ramadiyeh', district: 'Tyre' },
  { value: 'Rashkananiye', ar: "رشكنانية", en: 'Rashkananiye', district: 'Tyre' },
  { value: 'Shahour', ar: "شحور", en: 'Shahour', district: 'Tyre' },
  { value: 'Shaykhain', ar: "الشيخين", en: 'Shaykhain', district: 'Tyre' },
  { value: 'Shmaa', ar: "الشمع", en: 'Shmaa', district: 'Tyre' },
  { value: 'Sour', ar: "صور", en: 'Sour', district: 'Tyre' },
  { value: 'Srifa', ar: "صريفا", en: 'Srifa', district: 'Tyre' },
  { value: 'Tir Dibba', ar: "طير دبا", en: 'Tir Dibba', district: 'Tyre' },
  { value: 'Tura', ar: "طورا", en: 'Tura', district: 'Tyre' },
  { value: 'Tyr Felsay', ar: "صور فلسي", en: 'Tyr Felsay', district: 'Tyre' },
  { value: 'Yanouh', ar: "يانوح", en: 'Yanouh', district: 'Tyre' },
  { value: 'Yarine', ar: "يارين", en: 'Yarine', district: 'Tyre' },
  { value: 'Zabkin', ar: "زبقين", en: 'Zabkin', district: 'Tyre' },

  // --- Jezzine ---
  { value: 'Aarai', ar: "عرعي", en: 'Aarai', district: 'Jezzine' },
  { value: 'Al Maknouneh', ar: "المكنونة", en: 'Al Maknouneh', district: 'Jezzine' },
  { value: 'Al Midan', ar: "الميدان", en: 'Al Midan', district: 'Jezzine' },
  { value: 'Al-Eishiyeh', ar: "العيشية", en: 'Al-Eishiyeh', district: 'Jezzine' },
  { value: 'Al-Hamssiyeh', ar: "الحمصية", en: 'Al-Hamssiyeh', district: 'Jezzine' },
  { value: 'Al-Louwayzeh', ar: "اللويزة", en: 'Al-Louwayzeh', district: 'Jezzine' },
  { value: 'Al-Rayhan', ar: "الريحان", en: 'Al-Rayhan', district: 'Jezzine' },
  { value: 'Aramta', ar: "عرمتى", en: 'Aramta', district: 'Jezzine' },
  { value: 'Azour', ar: "عازور", en: 'Azour', district: 'Jezzine' },
  { value: 'Bkassine', ar: "بكاسين", en: 'Bkassine', district: 'Jezzine' },
  { value: 'Bnouhate', ar: "بنوحاتي", en: 'Bnouhate', district: 'Jezzine' },
  { value: 'Bteddine Al-Laqch', ar: "بتدين اللقش", en: 'Bteddine Al-Laqch', district: 'Jezzine' },
  { value: 'Haytoura', ar: "حيطورة", en: 'Haytoura', district: 'Jezzine' },
  { value: 'Jezzine', ar: "جزين", en: 'Jezzine', district: 'Jezzine' },
  { value: 'Jrania', ar: "الجرنية", en: 'Jrania', district: 'Jezzine' },
  { value: 'Karkha', ar: "قرخا", en: 'Karkha', district: 'Jezzine' },
  { value: 'Kfar Jirra', ar: "كفر جرّة", en: 'Kfar Jirra', district: 'Jezzine' },
  { value: 'Kfarfalous', ar: "كفرفلوس", en: 'Kfarfalous', district: 'Jezzine' },
  { value: 'Labaa', ar: "لبعا", en: 'Labaa', district: 'Jezzine' },
  { value: 'Majdal', ar: "مجدل", en: 'Majdal', district: 'Jezzine' },
  { value: 'Mchmoush', ar: "مشموش", en: 'Mchmoush', district: 'Jezzine' },
  { value: 'Mleih', ar: "مليح", en: 'Mleih', district: 'Jezzine' },
  { value: 'Qaitouli', ar: "قيتولي", en: 'Qaitouli', district: 'Jezzine' },
  { value: 'Qattin and Haidab', ar: "قطين وحيدب", en: 'Qattin and Haidab', district: 'Jezzine' },
  { value: 'Raymat and Shqadif', ar: "ريمات وشقاديف", en: 'Raymat and Shqadif', district: 'Jezzine' },
  { value: 'Roum', ar: "روم", en: 'Roum', district: 'Jezzine' },
  { value: 'Sabah', ar: "صباح", en: 'Sabah', district: 'Jezzine' },
  { value: 'Safarayya', ar: "صفاريا", en: 'Safarayya', district: 'Jezzine' },
  { value: 'Saniyyeh', ar: "السنية", en: 'Saniyyeh', district: 'Jezzine' },
  { value: 'Sidon (Jezzine)', ar: "صيدا (جزين)", en: 'Sidon (Jezzine)', district: 'Jezzine' },
  { value: 'Sijd', ar: "سجد", en: 'Sijd', district: 'Jezzine' },
  { value: 'Wadi Jezzine', ar: "وادي جزين", en: 'Wadi Jezzine', district: 'Jezzine' },
  { value: 'Zahlta', ar: "زحلتا", en: 'Zahlta', district: 'Jezzine' },

  // =============================================
  // NABATIEH
  // =============================================

  // --- Nabatieh ---
  { value: 'Aaba (Nabatieh)', ar: "عبا (النبطية)", en: 'Aaba', district: 'Nabatieh' },
  { value: 'Adchit', ar: "عدشيت", en: 'Adchit', district: 'Nabatieh' },
  { value: 'Ain Qana', ar: "عين قانا", en: 'Ain Qana', district: 'Nabatieh' },
  { value: 'Al Kfour', ar: "الكفور", en: 'Al Kfour', district: 'Nabatieh' },
  { value: 'Al Qsaybeh', ar: "القصيبة", en: 'Al Qsaybeh', district: 'Nabatieh' },
  { value: 'Al-Sharkiya', ar: "الشرقية", en: 'Al-Sharkiya', district: 'Nabatieh' },
  { value: 'Ansar', ar: "أنصار", en: 'Ansar', district: 'Nabatieh' },
  { value: 'Arabsalim', ar: "عربصاليم", en: 'Arabsalim', district: 'Nabatieh' },
  { value: 'Arnoun', ar: "أرنون", en: 'Arnoun', district: 'Nabatieh' },
  { value: 'Bariqaa', ar: "بريقع", en: 'Bariqaa', district: 'Nabatieh' },
  { value: 'Choukeen', ar: "شوكين", en: 'Choukeen', district: 'Nabatieh' },
  { value: 'Deir Al-Zahrani', ar: "دير الزهراني", en: 'Deir Al-Zahrani', district: 'Nabatieh' },
  { value: 'Doueir', ar: "الدوير", en: 'Doueir', district: 'Nabatieh' },
  { value: 'Ezza', ar: "عزة", en: 'Ezza', district: 'Nabatieh' },
  { value: 'Habbouch', ar: "حبوش", en: 'Habbouch', district: 'Nabatieh' },
  { value: 'Harouf', ar: "حاروف", en: 'Harouf', district: 'Nabatieh' },
  { value: 'Houmine Al-Fawqa', ar: "حومين الفوقا", en: 'Houmine Al-Fawqa', district: 'Nabatieh' },
  { value: 'Houmine Al-Tahta', ar: "حومين التحتا", en: 'Houmine Al-Tahta', district: 'Nabatieh' },
  { value: 'Jargea', ar: "جرجوع", en: 'Jargea', district: 'Nabatieh' },
  { value: 'Jbaa (Nabatieh)', ar: "جباع (النبطية)", en: 'Jbaa', district: 'Nabatieh' },
  { value: 'Jibchit', ar: "جبشيت", en: 'Jibchit', district: 'Nabatieh' },
  { value: 'Kaakaiye Bridge', ar: "جسر القعقعية", en: 'Kaakaiye Bridge', district: 'Nabatieh' },
  { value: 'Kafr Fila', ar: "كفرفيلا", en: 'Kafr Fila', district: 'Nabatieh' },
  { value: 'Kafr Ruman', ar: "كفررمان", en: 'Kafr Ruman', district: 'Nabatieh' },
  { value: 'Kafr Sir', ar: "كفرصير", en: 'Kafr Sir', district: 'Nabatieh' },
  { value: 'Kafr Tibnit', ar: "كفرتبنيت", en: 'Kafr Tibnit', district: 'Nabatieh' },
  { value: 'Mayfadoun', ar: "ميفدون", en: 'Mayfadoun', district: 'Nabatieh' },
  { value: 'Nabatieh', ar: "النبطية", en: 'Nabatieh', district: 'Nabatieh' },
  { value: 'Nabatieh Al-Fawqa', ar: "النبطية الفوقا", en: 'Nabatieh Al-Fawqa', district: 'Nabatieh' },
  { value: 'Nemriye', ar: "النميرية", en: 'Nemriye', district: 'Nabatieh' },
  { value: 'Rumine', ar: "رومين", en: 'Rumine', district: 'Nabatieh' },
  { value: 'Sair Al-Gharbiya', ar: "صير الغربية", en: 'Sair Al-Gharbiya', district: 'Nabatieh' },
  { value: 'Sarbah', ar: "صربا", en: 'Sarbah', district: 'Nabatieh' },
  { value: 'Seen', ar: "سين", en: 'Seen', district: 'Nabatieh' },
  { value: 'Yohmor', ar: "يحمر", en: 'Yohmor', district: 'Nabatieh' },
  { value: 'Zawtar Al-Gharbiya', ar: "زوطر الغربية", en: 'Zawtar Al-Gharbiya', district: 'Nabatieh' },
  { value: 'Zawtar Al-Sharkiya', ar: "زوطر الشرقية", en: 'Zawtar Al-Sharkiya', district: 'Nabatieh' },
  { value: 'Zefta', ar: "زفتا", en: 'Zefta', district: 'Nabatieh' },
  { value: 'Zibdeen', ar: "زبدين", en: 'Zibdeen', district: 'Nabatieh' },

  // --- Bint Jbeil ---
  { value: 'Ainata', ar: "عيناتا", en: 'Ainata', district: 'Bint Jbeil' },
  { value: 'Aita Al-Jabal', ar: "عيتا الجبل", en: 'Aita Al-Jabal', district: 'Bint Jbeil' },
  { value: 'Aitroun', ar: "عيترون", en: 'Aitroun', district: 'Bint Jbeil' },
  { value: 'Al Tireh', ar: "الطيرة", en: 'Al Tireh', district: 'Bint Jbeil' },
  { value: 'Baraachit', ar: "براعشيت", en: 'Baraachit', district: 'Bint Jbeil' },
  { value: 'Beit Leif', ar: "بيت ليف", en: 'Beit Leif', district: 'Bint Jbeil' },
  { value: 'Bint Jbeil', ar: "بنت جبيل", en: 'Bint Jbeil', district: 'Bint Jbeil' },
  { value: 'Deir Antar', ar: "دير عنتر", en: 'Deir Antar', district: 'Bint Jbeil' },
  { value: 'Haris', ar: "حاريص", en: 'Haris', district: 'Bint Jbeil' },
  { value: 'Jammijmeh', ar: "جمجم", en: 'Jammijmeh', district: 'Bint Jbeil' },
  { value: 'Kafr Dounin', ar: "كفردونين", en: 'Kafr Dounin', district: 'Bint Jbeil' },
  { value: 'Kounine', ar: "كونين", en: 'Kounine', district: 'Bint Jbeil' },
  { value: 'Kufra', ar: "كفرا", en: 'Kufra', district: 'Bint Jbeil' },
  { value: 'Maroun Ras El', ar: "مارون الراس", en: 'Maroun Ras El', district: 'Bint Jbeil' },
  { value: 'Qalawayh', ar: "قلاويه", en: 'Qalawayh', district: 'Bint Jbeil' },
  { value: 'Safad El Batikh', ar: "صفد البطيخ", en: 'Safad El Batikh', district: 'Bint Jbeil' },
  { value: 'Tebnine', ar: "تبنين", en: 'Tebnine', district: 'Bint Jbeil' },
  { value: 'Yater', ar: "ياطر", en: 'Yater', district: 'Bint Jbeil' },

  // --- Marjeyoun ---
  { value: 'Ain Qenya (Marjeyoun)', ar: "عين قنية (مرجعيون)", en: 'Ain Qenya', district: 'Marjeyoun' },
  { value: 'Al-Kafr (Marjeyoun)', ar: "الكفر (مرجعيون)", en: 'Al-Kafr', district: 'Marjeyoun' },
  { value: 'Al-Khalwat (Marjeyoun)', ar: "الخلوات (مرجعيون)", en: 'Al-Khalwat', district: 'Marjeyoun' },
  { value: 'Hasbaya (Marjeyoun)', ar: "حصبيا (مرجعيون)", en: 'Hasbaya', district: 'Marjeyoun' },
  { value: 'Kawkaba (Marjeyoun)', ar: "كوكبا (مرجعيون)", en: 'Kawkaba', district: 'Marjeyoun' },
  { value: 'Marj al-Zuhur (Marjeyoun)', ar: "مرج الزهور (مرجعيون)", en: 'Marj al-Zuhur', district: 'Marjeyoun' },
  { value: 'Mimas (Marjeyoun)', ar: "ميماس (مرجعيون)", en: 'Mimas', district: 'Marjeyoun' },
  { value: 'Shwaya (Marjeyoun)', ar: "شويا (مرجعيون)", en: 'Shwaya', district: 'Marjeyoun' },

  // --- Hasbaya ---
  { value: 'Ain Qenya (Hasbaya)', ar: "عين قنية (حصبيا)", en: 'Ain Qenya', district: 'Hasbaya' },
  { value: 'Al-Fardis', ar: "الفردس", en: 'Al-Fardis', district: 'Hasbaya' },
  { value: 'Al-Habariyah', ar: "الهبارية", en: 'Al-Habariyah', district: 'Hasbaya' },
  { value: 'Al-Kafr (Hasbaya)', ar: "الكفر (حصبيا)", en: 'Al-Kafr', district: 'Hasbaya' },
  { value: 'Al-Khalwat (Hasbaya)', ar: "الخلوات (حصبيا)", en: 'Al-Khalwat', district: 'Hasbaya' },
  { value: 'Hasbaya', ar: "حصبيا", en: 'Hasbaya', district: 'Hasbaya' },
  { value: 'Kafr Hammam', ar: "كفرحمام", en: 'Kafr Hammam', district: 'Hasbaya' },
  { value: 'Kafr Shuba', ar: "كفرشوبا", en: 'Kafr Shuba', district: 'Hasbaya' },
  { value: 'Kawkaba (Hasbaya)', ar: "كوكبا (حصبيا)", en: 'Kawkaba', district: 'Hasbaya' },
  { value: 'Majideyah wa Marieh', ar: "المجيدية ومرية", en: 'Majideyah wa Marieh', district: 'Hasbaya' },
  { value: 'Marj al-Zuhur (Hasbaya)', ar: "مرج الزهور (حصبيا)", en: 'Marj al-Zuhur', district: 'Hasbaya' },
  { value: 'Mimas (Hasbaya)', ar: "ميماس (حصبيا)", en: 'Mimas', district: 'Hasbaya' },
  { value: 'Rashaya al-Fukhar', ar: "راشيا الفخار", en: 'Rashaya al-Fukhar', district: 'Hasbaya' },
  { value: 'Shebaa', ar: "شبعا", en: 'Shebaa', district: 'Hasbaya' },
  { value: 'Shwaya (Hasbaya)', ar: "شويا (حصبيا)", en: 'Shwaya', district: 'Hasbaya' },

  // =============================================
  // BEQAA
  // =============================================

  // --- Zahle ---
  { value: 'Abilh', ar: "عبيله", en: 'Abilh', district: 'Zahle' },
  { value: 'Ain Kafarzabad', ar: "عين كفرزبد", en: 'Ain Kafarzabad', district: 'Zahle' },
  { value: 'Ali Al-Nahri', ar: "علي النهري", en: 'Ali Al-Nahri', district: 'Zahle' },
  { value: 'Bar Elias', ar: "بر الياس", en: 'Bar Elias', district: 'Zahle' },
  { value: 'Bawarj', ar: "البوارج", en: 'Bawarj', district: 'Zahle' },
  { value: 'Chatura', ar: "شتورا", en: 'Chatura', district: 'Zahle' },
  { value: 'Deir Al-Ghazal', ar: "دير الغزال", en: 'Deir Al-Ghazal', district: 'Zahle' },
  { value: 'Ferzol', ar: "فرزل", en: 'Ferzol', district: 'Zahle' },
  { value: 'Hay Al-Fikani', ar: "حي الفيكاني", en: 'Hay Al-Fikani', district: 'Zahle' },
  { value: 'Hazerta', ar: "حزرتا", en: 'Hazerta', district: 'Zahle' },
  { value: 'Hosh Moussa', ar: "حوش موسى", en: 'Hosh Moussa', district: 'Zahle' },
  { value: 'Kfarzabad', ar: "كفرزبد", en: 'Kfarzabad', district: 'Zahle' },
  { value: 'Maaloula and Taanayel', ar: "معلولا وتعنايل", en: 'Maaloula and Taanayel', district: 'Zahle' },
  { value: 'Majdal Anjar', ar: "مجدل عنجر", en: 'Majdal Anjar', district: 'Zahle' },
  { value: 'Makse', ar: "مكسة", en: 'Makse', district: 'Zahle' },
  { value: 'Massa', ar: "ماسا", en: 'Massa', district: 'Zahle' },
  { value: 'Mrayjet (Zahle)', ar: "المريجات (زحلة)", en: 'Mrayjet', district: 'Zahle' },
  { value: 'Nasiriya', ar: "الناصرية", en: 'Nasiriya', district: 'Zahle' },
  { value: 'Niha (Zahle)', ar: "نيحا (زحلة)", en: 'Niha', district: 'Zahle' },
  { value: 'Qob Elias', ar: "قب الياس", en: 'Qob Elias', district: 'Zahle' },
  { value: 'Qousaya', ar: "قوسايا", en: 'Qousaya', district: 'Zahle' },
  { value: 'Riak', ar: "رياق", en: 'Riak', district: 'Zahle' },
  { value: 'Riyat', ar: "ريات", en: 'Riyat', district: 'Zahle' },
  { value: 'Saadnayel', ar: "سعدنايل", en: 'Saadnayel', district: 'Zahle' },
  { value: 'Talabayya', ar: "تعلبايا", en: 'Talabayya', district: 'Zahle' },
  { value: 'Trebil', ar: "تربل", en: 'Trebil', district: 'Zahle' },
  { value: 'Zahle', ar: "زحلة", en: 'Zahle', district: 'Zahle' },

  // --- Western Beqaa ---
  { value: 'Aana', ar: "عنا", en: 'Aana', district: 'Western Beqaa' },
  { value: 'Ain El Tinah', ar: "عين التينة", en: 'Ain El Tinah', district: 'Western Beqaa' },
  { value: 'Ain Zabda', ar: "عين زبدة", en: 'Ain Zabda', district: 'Western Beqaa' },
  { value: 'Al Manara', ar: "المنارة", en: 'Al Manara', district: 'Western Beqaa' },
  { value: 'Al Mansoura', ar: "المنصورة", en: 'Al Mansoura', district: 'Western Beqaa' },
  { value: 'Al Rawda', ar: "الروضة", en: 'Al Rawda', district: 'Western Beqaa' },
  { value: 'Al-Khiyara', ar: "الخيارة", en: 'Al-Khiyara', district: 'Western Beqaa' },
  { value: 'Al-Muruj', ar: "المروج", en: 'Al-Muruj', district: 'Western Beqaa' },
  { value: 'Al-Sawiri', ar: "الصويري", en: 'Al-Sawiri', district: 'Western Beqaa' },
  { value: 'Ameq', ar: "عميق", en: 'Ameq', district: 'Western Beqaa' },
  { value: 'Aytanit', ar: "عيتنيت", en: 'Aytanit', district: 'Western Beqaa' },
  { value: "Ba'loul", ar: "بعلول", en: "Ba'loul", district: 'Western Beqaa' },
  { value: "Bab Mare'", ar: "باب مارع", en: "Bab Mare'", district: 'Western Beqaa' },
  { value: 'Gaza', ar: "غزة", en: 'Gaza', district: 'Western Beqaa' },
  { value: 'Hosh Al-Harimeh', ar: "حوش الحريمة", en: 'Hosh Al-Harimeh', district: 'Western Beqaa' },
  { value: 'Jaba Jenin', ar: "جب جنين", en: 'Jaba Jenin', district: 'Western Beqaa' },
  { value: 'Kafraya', ar: "كفريا", en: 'Kafraya', district: 'Western Beqaa' },
  { value: 'Kamid Al-Lawz', ar: "كامد اللوز", en: 'Kamid Al-Lawz', district: 'Western Beqaa' },
  { value: 'Khirbet Qanafar', ar: "خربة قنافار", en: 'Khirbet Qanafar', district: 'Western Beqaa' },
  { value: 'Lala', ar: "لالا", en: 'Lala', district: 'Western Beqaa' },
  { value: 'Lubya', ar: "اللوبية", en: 'Lubya', district: 'Western Beqaa' },
  { value: 'Mashgharah', ar: "مشغرة", en: 'Mashgharah', district: 'Western Beqaa' },
  { value: 'Midoun and Lussia', ar: "ميدون ولوسيا", en: 'Midoun and Lussia', district: 'Western Beqaa' },
  { value: 'Qarawat Bani Hassan', ar: "قرعون بني حسن", en: 'Qarawat Bani Hassan', district: 'Western Beqaa' },
  { value: 'Qilya', ar: "قليا", en: 'Qilya', district: 'Western Beqaa' },
  { value: 'Saghbin', ar: "سغبين", en: 'Saghbin', district: 'Western Beqaa' },
  { value: 'Sahmara', ar: "صحمر", en: 'Sahmara', district: 'Western Beqaa' },
  { value: "Sultan Ya'qub", ar: "سلطان يعقوب", en: "Sultan Ya'qub", district: 'Western Beqaa' },
  { value: 'Tall Dzanoub', ar: "تل ذنوب", en: 'Tall Dzanoub', district: 'Western Beqaa' },
  { value: 'Yahmar', ar: "يحمر", en: 'Yahmar', district: 'Western Beqaa' },
  { value: 'Zalaya', ar: "زلايا", en: 'Zalaya', district: 'Western Beqaa' },

  // --- Rachaya ---
  { value: 'Ain Arab', ar: "عين عرب", en: 'Ain Arab', district: 'Rachaya' },
  { value: 'Ain Ata', ar: "عين عطا", en: 'Ain Ata', district: 'Rachaya' },
  { value: 'Ain Harsha', ar: "عين حرشا", en: 'Ain Harsha', district: 'Rachaya' },
  { value: 'Al-Aqaba', ar: "العقبة", en: 'Al-Aqaba', district: 'Rachaya' },
  { value: 'Al-Bireh (Rachaya)', ar: "البيرة (راشيا)", en: 'Al-Bireh', district: 'Rachaya' },
  { value: 'Al-Muheithrah', ar: "المهيثرة", en: 'Al-Muheithrah', district: 'Rachaya' },
  { value: 'Al-Rafid', ar: "الرفيد", en: 'Al-Rafid', district: 'Rachaya' },
  { value: 'Beit Lahia', ar: "بيت لهيا", en: 'Beit Lahia', district: 'Rachaya' },
  { value: 'Bkaa', ar: "بكا", en: 'Bkaa', district: 'Rachaya' },
  { value: 'Bkifa', ar: "بكيفا", en: 'Bkifa', district: 'Rachaya' },
  { value: 'Deir Al-Ashayer', ar: "دير العشاير", en: 'Deir Al-Ashayer', district: 'Rachaya' },
  { value: 'Eita Al-Fakhar', ar: "عيتا الفخار", en: 'Eita Al-Fakhar', district: 'Rachaya' },
  { value: 'Eyha', ar: "عيحا", en: 'Eyha', district: 'Rachaya' },
  { value: 'Halawa', ar: "حلاوة", en: 'Halawa', district: 'Rachaya' },
  { value: 'Hosh Al-Qanaba', ar: "حوش القنابة", en: 'Hosh Al-Qanaba', district: 'Rachaya' },
  { value: 'Kafr Danis', ar: "كفردانس", en: 'Kafr Danis', district: 'Rachaya' },
  { value: 'Kafr Mashki', ar: "كفرمشكي", en: 'Kafr Mashki', district: 'Rachaya' },
  { value: 'Kafr Qouq', ar: "كفرقوق", en: 'Kafr Qouq', district: 'Rachaya' },
  { value: 'Kawkaba (Rachaya)', ar: "كوكبا (راشيا)", en: 'Kawkaba', district: 'Rachaya' },
  { value: 'Khirbet Rouha', ar: "خربة روحا", en: 'Khirbet Rouha', district: 'Rachaya' },
  { value: 'Majdal Bani Fadel', ar: "مجدل بني فاضل", en: 'Majdal Bani Fadel', district: 'Rachaya' },
  { value: 'Mudawwara', ar: "المدورة", en: 'Mudawwara', district: 'Rachaya' },
  { value: 'Rashaya', ar: "راشيا", en: 'Rashaya', district: 'Rachaya' },
  { value: 'Tannourine (Rachaya)', ar: "تنورين (راشيا)", en: 'Tannourine', district: 'Rachaya' },
  { value: 'Yanta', ar: "ينطا", en: 'Yanta', district: 'Rachaya' },
  { value: 'Zahr Al-Ahmar', ar: "ظهر الأحمر", en: 'Zahr Al-Ahmar', district: 'Rachaya' },

  // =============================================
  // BAALBEK-HERMEL
  // =============================================

  // --- Baalbek ---
  { value: 'Ainata (Baalbek)', ar: "عيناتا (بعلبك)", en: 'Ainata', district: 'Baalbek' },
  { value: 'Al Ansar', ar: "الأنصار", en: 'Al Ansar', district: 'Baalbek' },
  { value: 'Al Khreibeh', ar: "الخريبة", en: 'Al Khreibeh', district: 'Baalbek' },
  { value: 'Al Khudr', ar: "الخضر", en: 'Al Khudr', district: 'Baalbek' },
  { value: 'Al Ram and Al Jubayniyah', ar: "الرام والجبينية", en: 'Al Ram and Al Jubayniyah', district: 'Baalbek' },
  { value: 'Al Tawfiqiyah', ar: "التوفيقية", en: 'Al Tawfiqiyah', district: 'Baalbek' },
  { value: 'Al Zarazir', ar: "الزرازير", en: 'Al Zarazir', district: 'Baalbek' },
  { value: 'Al-Ain', ar: "العين", en: 'Al-Ain', district: 'Baalbek' },
  { value: 'Al-Laboue', ar: "اللبوة", en: 'Al-Laboue', district: 'Baalbek' },
  { value: 'Al-Nabi Othman', ar: "النبي عثمان", en: 'Al-Nabi Othman', district: 'Baalbek' },
  { value: 'Al-Nabi Sheet', ar: "النبي شيت", en: 'Al-Nabi Sheet', district: 'Baalbek' },
  { value: 'Al-Saeeda', ar: "السعيدة", en: 'Al-Saeeda', district: 'Baalbek' },
  { value: 'Baalbek', ar: "بعلبك", en: 'Baalbek', district: 'Baalbek' },
  { value: 'Barqa', ar: "برقا", en: 'Barqa', district: 'Baalbek' },
  { value: 'Bdenayel', ar: "بدنايل", en: 'Bdenayel', district: 'Baalbek' },
  { value: 'Beit Shama', ar: "بيت شاما", en: 'Beit Shama', district: 'Baalbek' },
  { value: 'Bishwat', ar: "بشوات", en: 'Bishwat', district: 'Baalbek' },
  { value: 'Boudai and Al Alaqa', ar: "بودي والعلاقة", en: 'Boudai and Al Alaqa', district: 'Baalbek' },
  { value: 'Brital', ar: "بريتال", en: 'Brital', district: 'Baalbek' },
  { value: 'Btedai', ar: "بتدعي", en: 'Btedai', district: 'Baalbek' },
  { value: 'Deir Al Ahmar', ar: "دير الأحمر", en: 'Deir Al Ahmar', district: 'Baalbek' },
  { value: 'Douris', ar: "دورس", en: 'Douris', district: 'Baalbek' },
  { value: 'Flawi', ar: "فلاوي", en: 'Flawi', district: 'Baalbek' },
  { value: 'Hadath Baalbek', ar: "حدث بعلبك", en: 'Hadath Baalbek', district: 'Baalbek' },
  { value: 'Halabat', ar: "حلبتا", en: 'Halabat', district: 'Baalbek' },
  { value: 'Harbata', ar: "حربتا", en: 'Harbata', district: 'Baalbek' },
  { value: 'Hawsh Al Nabi', ar: "حوش النبي", en: 'Hawsh Al Nabi', district: 'Baalbek' },
  { value: 'Hawsh Al Rafiqah', ar: "حوش الرافقة", en: 'Hawsh Al Rafiqah', district: 'Baalbek' },
  { value: 'Hawsh Saneed', ar: "حوش سنيد", en: 'Hawsh Saneed', district: 'Baalbek' },
  { value: 'Hazin', ar: "حزين", en: 'Hazin', district: 'Baalbek' },
  { value: 'Houch Berda', ar: "حوش برده", en: 'Houch Berda', district: 'Baalbek' },
  { value: 'Houch Tel Safiye', ar: "حوش تل صفية", en: 'Houch Tel Safiye', district: 'Baalbek' },
  { value: 'Hurit Alaa', ar: "حورتعلا", en: 'Hurit Alaa', district: 'Baalbek' },
  { value: 'Iaat', ar: "إيعات", en: 'Iaat', district: 'Baalbek' },
  { value: "Jaba'a (Baalbek)", ar: "جبعا (بعلبك)", en: "Jaba'a", district: 'Baalbek' },
  { value: 'Jabule', ar: "جبولة", en: 'Jabule', district: 'Baalbek' },
  { value: 'Jinta', ar: "جنتا", en: 'Jinta', district: 'Baalbek' },
  { value: 'Kfardan', ar: "كفردان", en: 'Kfardan', district: 'Baalbek' },
  { value: "Ma'arabun", ar: "معربون", en: "Ma'arabun", district: 'Baalbek' },
  { value: 'Majdaloun', ar: "مجدلون", en: 'Majdaloun', district: 'Baalbek' },
  { value: 'Mqneh', ar: "مقنة", en: 'Mqneh', district: 'Baalbek' },
  { value: 'Nabha Al Dumdum', ar: "نبحا الدمدوم", en: 'Nabha Al Dumdum', district: 'Baalbek' },
  { value: 'Nabha Al Mahfara', ar: "نبحا المحفرة", en: 'Nabha Al Mahfara', district: 'Baalbek' },
  { value: 'Nabha Al Qadam', ar: "نبحا القدم", en: 'Nabha Al Qadam', district: 'Baalbek' },
  { value: 'Nahle', ar: "النحلة", en: 'Nahle', district: 'Baalbek' },
  { value: 'Qaleela and Harfoush', ar: "قليلة وحرفوش", en: 'Qaleela and Harfoush', district: 'Baalbek' },
  { value: 'Qarah', ar: "قارة", en: 'Qarah', district: 'Baalbek' },
  { value: 'Qasr Naba', ar: "قصر نبا", en: 'Qasr Naba', district: 'Baalbek' },
  { value: 'Sareen Al-Fawqa', ar: "سرعين الفوقا", en: 'Sareen Al-Fawqa', district: 'Baalbek' },
  { value: 'Serain Al Tahta', ar: "سرعين التحتا", en: 'Serain Al Tahta', district: 'Baalbek' },
  { value: 'Shaath', ar: "شعث", en: 'Shaath', district: 'Baalbek' },
  { value: 'Shamstaar', ar: "شمسطار", en: 'Shamstaar', district: 'Baalbek' },
  { value: 'Talya', ar: "تليا", en: 'Talya', district: 'Baalbek' },
  { value: 'Tannin Al Foqa', ar: "تنين الفوقا", en: 'Tannin Al Foqa', district: 'Baalbek' },
  { value: 'Tannin Al Tahta', ar: "تنين التحتا", en: 'Tannin Al Tahta', district: 'Baalbek' },
  { value: 'Tariya', ar: "طارية", en: 'Tariya', district: 'Baalbek' },
  { value: "Wadi Fa'rah", ar: "وادي فعرة", en: "Wadi Fa'rah", district: 'Baalbek' },
  { value: 'Yunin', ar: "اليونين", en: 'Yunin', district: 'Baalbek' },
  { value: 'Zabud', ar: "زبود", en: 'Zabud', district: 'Baalbek' },

  // --- Hermel ---
  { value: 'Al Hermel', ar: "الهرمل", en: 'Al Hermel', district: 'Hermel' },
  { value: 'Al Kawakh', ar: "الكواخ", en: 'Al Kawakh', district: 'Hermel' },
  { value: 'Al Qasr', ar: "القصر", en: 'Al Qasr', district: 'Hermel' },
  { value: 'Al Shawagir', ar: "الشواغير", en: 'Al Shawagir', district: 'Hermel' },
  { value: 'Fissan', ar: "فيسان", en: 'Fissan', district: 'Hermel' },
  { value: 'Jawar Al Hashish', ar: "جوار الحشيش", en: 'Jawar Al Hashish', district: 'Hermel' },
];

/**
 * Get districts for a given governorate.
 * For Beirut/Akkar (single district), returns that one district.
 */
export function getDistrictsForGovernorate(governorate) {
  return DISTRICTS.filter((d) => d.governorate === governorate);
}

/**
 * Get municipalities for a given district.
 * Returns empty until municipality data is provided.
 */
export function getMunicipalitiesForDistrict(district) {
  return MUNICIPALITIES.filter((m) => m.district === district);
}

/**
 * Check if a governorate has only one district (auto-select it).
 */
export function isSingleDistrictGovernorate(governorate) {
  return getDistrictsForGovernorate(governorate).length === 1;
}