/**
 * Lebanese administrative divisions: Governorate -> District -> Municipality.
 * Municipality data will be added later per district.
 */

export const GOVERNORATES = [
  { value: 'Beirut', ar: 'بيروت', en: 'Beirut' },
  { value: 'Mount Lebanon', ar: 'جبل لبنان', en: 'Mount Lebanon' },
  { value: 'North Lebanon', ar: 'لبنان الشمالي', en: 'North Lebanon' },
  { value: 'Akkar', ar: 'عكار', en: 'Akkar' },
  { value: 'South Lebanon', ar: 'لبنان الجنوبي', en: 'South Lebanon' },
  { value: 'Nabatieh', ar: 'النبطية', en: 'Nabatieh' },
  { value: 'Beqaa', ar: 'البقاع', en: 'Beqaa' },
  { value: 'Baalbek-Hermel', ar: 'بعلبك-الهرمل', en: 'Baalbek-Hermel' },
];

export const DISTRICTS = [
  // Beirut — single district, auto-selected
  { value: 'Beirut', ar: 'بيروت', en: 'Beirut', governorate: 'Beirut' },

  // Mount Lebanon
  { value: 'Baabda', ar: 'بعبدا', en: 'Baabda', governorate: 'Mount Lebanon' },
  { value: 'Aley', ar: 'عاليه', en: 'Aley', governorate: 'Mount Lebanon' },
  { value: 'Chouf', ar: 'الشوف', en: 'Chouf', governorate: 'Mount Lebanon' },
  { value: 'Keserwan', ar: 'كسروان', en: 'Keserwan', governorate: 'Mount Lebanon' },
  { value: 'Metn', ar: 'المتن', en: 'Metn', governorate: 'Mount Lebanon' },
  { value: 'Jbeil', ar: 'جبيل', en: 'Jbeil', governorate: 'Mount Lebanon' },

  // North Lebanon
  { value: 'Tripoli', ar: 'طرابلس', en: 'Tripoli', governorate: 'North Lebanon' },
  { value: 'Zgharta', ar: 'زغرتا', en: 'Zgharta', governorate: 'North Lebanon' },
  { value: 'Koura', ar: 'الكورة', en: 'Koura', governorate: 'North Lebanon' },
  { value: 'Bsharri', ar: 'بشري', en: 'Bsharri', governorate: 'North Lebanon' },
  { value: 'Batroun', ar: 'البترون', en: 'Batroun', governorate: 'North Lebanon' },
  { value: 'Miniyeh-Danniyeh', ar: 'المنية-الضنية', en: 'Miniyeh-Danniyeh', governorate: 'North Lebanon' },

  // Akkar — single district
  { value: 'Akkar', ar: 'عكار', en: 'Akkar', governorate: 'Akkar' },

  // South Lebanon
  { value: 'Sidon', ar: 'صيدا', en: 'Sidon', governorate: 'South Lebanon' },
  { value: 'Tyre', ar: 'صور', en: 'Tyre', governorate: 'South Lebanon' },
  { value: 'Jezzine', ar: 'جزين', en: 'Jezzine', governorate: 'South Lebanon' },

  // Nabatieh
  { value: 'Nabatieh', ar: 'النبطية', en: 'Nabatieh', governorate: 'Nabatieh' },
  { value: 'Hasbaya', ar: 'حاصبيا', en: 'Hasbaya', governorate: 'Nabatieh' },
  { value: 'Marjeyoun', ar: 'مرجعيون', en: 'Marjeyoun', governorate: 'Nabatieh' },
  { value: 'Bint Jbeil', ar: 'بنت جبيل', en: 'Bint Jbeil', governorate: 'Nabatieh' },

  // Beqaa
  { value: 'Zahle', ar: 'زحلة', en: 'Zahle', governorate: 'Beqaa' },
  { value: 'Western Beqaa', ar: 'البقاع الغربي', en: 'Western Beqaa', governorate: 'Beqaa' },
  { value: 'Rachaya', ar: 'راشيا', en: 'Rachaya', governorate: 'Beqaa' },

  // Baalbek-Hermel
  { value: 'Baalbek', ar: 'بعلبك', en: 'Baalbek', governorate: 'Baalbek-Hermel' },
  { value: 'Hermel', ar: 'الهرمل', en: 'Hermel', governorate: 'Baalbek-Hermel' },
];

// Municipalities — North Lebanon (from official registry data)
// Other governorates to be added when data is available.
export const MUNICIPALITIES = [
  // --- Koura ---
  { value: 'Aaba', en: 'Aaba', district: 'Koura' },
  { value: 'Afusdiq', en: 'Afusdiq', district: 'Koura' },
  { value: 'Ain Aakrine', en: 'Ain Aakrine', district: 'Koura' },
  { value: 'Ajdabrin', en: 'Ajdabrin', district: 'Koura' },
  { value: 'Al-Majdal', en: 'Al-Majdal', district: 'Koura' },
  { value: 'Amyoun', en: 'Amyoun', district: 'Koura' },
  { value: 'Anfeh', en: 'Anfeh', district: 'Koura' },
  { value: 'Bassirma', en: 'Bassirma', district: 'Koura' },
  { value: 'Batram', en: 'Batram', district: 'Koura' },
  { value: 'Batroumine', en: 'Batroumine', district: 'Koura' },
  { value: 'Bchamzin', en: 'Bchamzin', district: 'Koura' },
  { value: 'Bdebba', en: 'Bdebba', district: 'Koura' },
  { value: 'Bdenaile', en: 'Bdenaile', district: 'Koura' },
  { value: 'Bennihraan', en: 'Bennihraan', district: 'Koura' },
  { value: 'Bkaftine', en: 'Bkaftine', district: 'Koura' },
  { value: 'Btaaboura', en: 'Btaaboura', district: 'Koura' },
  { value: 'Btouratije', en: 'Btouratije', district: 'Koura' },
  { value: 'Bursa', en: 'Bursa', district: 'Koura' },
  { value: 'Bziza', en: 'Bziza', district: 'Koura' },
  { value: 'Dar Bechtar', en: 'Dar Bechtar', district: 'Koura' },
  { value: 'Dar Chmizzine', en: 'Dar Chmizzine', district: 'Koura' },
  { value: 'Dede', en: 'Dede', district: 'Koura' },
  { value: 'Fiyeh', en: 'Fiyeh', district: 'Koura' },
  { value: 'Kaftoun', en: 'Kaftoun', district: 'Koura' },
  { value: 'Kfarahezir', en: 'Kfarahezir', district: 'Koura' },
  { value: 'Kfaraka', en: 'Kfaraka', district: 'Koura' },
  { value: 'Kfarhatta', en: 'Kfarhatta', district: 'Koura' },
  { value: 'Kfarsaroun', en: 'Kfarsaroun', district: 'Koura' },
  { value: 'Kfraya', en: 'Kfraya', district: 'Koura' },
  { value: 'Kousba', en: 'Kousba', district: 'Koura' },
  { value: 'Metrith', en: 'Metrith', district: 'Koura' },
  { value: 'Qolehate', en: 'Qolehate', district: 'Koura' },
  { value: 'Rachadbin', en: 'Rachadbin', district: 'Koura' },

  // --- Batroun ---
  { value: 'Aabrin', en: 'Aabrin', district: 'Batroun' },
  { value: 'Adah', en: 'Adah', district: 'Batroun' },
  { value: 'Ajdabra', en: 'Ajdabra', district: 'Batroun' },
  { value: 'Al Batroun', en: 'Al Batroun', district: 'Batroun' },
  { value: 'Al Heri', en: 'Al Heri', district: 'Batroun' },
  { value: 'Asia', en: 'Asia', district: 'Batroun' },
  { value: 'Beit Chlala', en: 'Beit Chlala', district: 'Batroun' },
  { value: 'Bqosta', en: 'Bqosta', district: 'Batroun' },
  { value: 'Bshaleh', en: 'Bshaleh', district: 'Batroun' },
  { value: 'Chatine', en: 'Chatine', district: 'Batroun' },
  { value: 'Deir Bela', en: 'Deir Bela', district: 'Batroun' },
  { value: 'Douma', en: 'Douma', district: 'Batroun' },
  { value: 'Hamat', en: 'Hamat', district: 'Batroun' },
  { value: 'Hardine', en: 'Hardine', district: 'Batroun' },
  { value: 'Jran', en: 'Jran', district: 'Batroun' },
  { value: 'Kfaraarabi', en: 'Kfaraarabi', district: 'Batroun' },
  { value: 'Kfarabida', en: 'Kfarabida', district: 'Batroun' },
  { value: 'Kfarchi', en: 'Kfarchi', district: 'Batroun' },
  { value: 'Kfarhelda', en: 'Kfarhelda', district: 'Batroun' },
  { value: 'Koubba', en: 'Koubba', district: 'Batroun' },
  { value: 'Kour', en: 'Kour', district: 'Batroun' },
  { value: 'Ras Nahash', en: 'Ras Nahash', district: 'Batroun' },
  { value: 'Salata', en: 'Salata', district: 'Batroun' },
  { value: 'Shbatin', en: 'Shbatin', district: 'Batroun' },
  { value: 'Tannourine', en: 'Tannourine', district: 'Batroun' },
  { value: 'Tehoum', en: 'Tehoum', district: 'Batroun' },
  { value: 'Zan', en: 'Zan', district: 'Batroun' },

  // --- Bsharri ---
  { value: 'Abdeen', en: 'Abdeen', district: 'Bsharri' },
  { value: 'Baan', en: 'Baan', district: 'Bsharri' },
  { value: 'Bazoun', en: 'Bazoun', district: 'Bsharri' },
  { value: 'Beqaa Kafra', en: 'Beqaa Kafra', district: 'Bsharri' },
  { value: 'Bkrkasha', en: 'Bkrkasha', district: 'Bsharri' },
  { value: 'Bsharri', en: 'Bsharri', district: 'Bsharri' },
  { value: 'Hadath El Jebbeh', en: 'Hadath El Jebbeh', district: 'Bsharri' },
  { value: 'Hassroun', en: 'Hassroun', district: 'Bsharri' },
  { value: 'Hdad Shaayt', en: 'Hdad Shaayt', district: 'Bsharri' },
  { value: 'Qannat', en: 'Qannat', district: 'Bsharri' },
  { value: 'Tourza', en: 'Tourza', district: 'Bsharri' },
  { value: 'Ayoan Al Bir', en: 'Ayoan Al Bir', district: 'Bsharri' },

  // --- Zgharta ---
  { value: 'Ain Tourine', en: 'Ain Tourine', district: 'Zgharta' },
  { value: 'Aito', en: 'Aito', district: 'Zgharta' },
  { value: 'Arbaat Qazhya', en: 'Arbaat Qazhya', district: 'Zgharta' },
  { value: 'Ardah', en: 'Ardah', district: 'Zgharta' },
  { value: 'Arjish', en: 'Arjish', district: 'Zgharta' },
  { value: 'Ashash', en: 'Ashash', district: 'Zgharta' },
  { value: 'Ayal', en: 'Ayal', district: 'Zgharta' },
  { value: 'Banshie', en: 'Banshie', district: 'Zgharta' },
  { value: 'Basliqit', en: 'Basliqit', district: 'Zgharta' },
  { value: 'Darya-Bishnin', en: 'Darya-Bishnin', district: 'Zgharta' },
  { value: 'Harat Al Fawar', en: 'Harat Al Fawar', district: 'Zgharta' },
  { value: 'Karm Sadeh', en: 'Karm Sadeh', district: 'Zgharta' },
  { value: 'Kfar Sghab', en: 'Kfar Sghab', district: 'Zgharta' },
  { value: 'Kfar Zina', en: 'Kfar Zina', district: 'Zgharta' },
  { value: 'Kfardfou', en: 'Kfardfou', district: 'Zgharta' },
  { value: 'Kfardlakos', en: 'Kfardlakos', district: 'Zgharta' },
  { value: 'Kfarhata', en: 'Kfarhata', district: 'Zgharta' },
  { value: 'Kfaryachit-Bassbaal', en: 'Kfaryachit-Bassbaal', district: 'Zgharta' },
  { value: 'Majdalia', en: 'Majdalia', district: 'Zgharta' },
  { value: 'Mazraat Al Tuffah', en: 'Mazraat Al Tuffah', district: 'Zgharta' },
  { value: 'Bash Qarah', en: 'Bash Qarah', district: 'Zgharta' },
  { value: 'Rachiine', en: 'Rachiine', district: 'Zgharta' },
  { value: 'Ras Kifa', en: 'Ras Kifa', district: 'Zgharta' },
  { value: 'Saraal', en: 'Saraal', district: 'Zgharta' },
  { value: 'Zgharta-Ehden', en: 'Zgharta-Ehden', district: 'Zgharta' },

  // --- Tripoli ---
  { value: 'Al-Badawi', en: 'Al-Badawi', district: 'Tripoli' },
  { value: 'Al-Mina', en: 'Al-Mina', district: 'Tripoli' },
  { value: 'Al-Qalamoun', en: 'Al-Qalamoun', district: 'Tripoli' },
  { value: 'Tripoli', en: 'Tripoli', district: 'Tripoli' },

  // --- Miniyeh-Danniyeh ---
  { value: 'Aimar', en: 'Aimar', district: 'Miniyeh-Danniyeh' },
  { value: 'Ain Al-Tineh', en: 'Ain Al-Tineh', district: 'Miniyeh-Danniyeh' },
  { value: 'Al-Hazmiyeh', en: 'Al-Hazmiyeh', district: 'Miniyeh-Danniyeh' },
  { value: 'Al-Minya', en: 'Al-Minya', district: 'Miniyeh-Danniyeh' },
  { value: 'Al-Safira', en: 'Al-Safira', district: 'Miniyeh-Danniyeh' },
  { value: 'Asoun', en: 'Asoun', district: 'Miniyeh-Danniyeh' },
  { value: 'Bahneen', en: 'Bahneen', district: 'Miniyeh-Danniyeh' },
  { value: 'Bakhoun', en: 'Bakhoun', district: 'Miniyeh-Danniyeh' },
  { value: 'Batarmaz', en: 'Batarmaz', district: 'Miniyeh-Danniyeh' },
  { value: 'Beit Al-Faqas', en: 'Beit Al-Faqas', district: 'Miniyeh-Danniyeh' },
  { value: 'Beqaa Safreen', en: 'Beqaa Safreen', district: 'Miniyeh-Danniyeh' },
  { value: 'Bshnata', en: 'Bshnata', district: 'Miniyeh-Danniyeh' },
  { value: 'Bqarsouna', en: 'Bqarsouna', district: 'Miniyeh-Danniyeh' },
  { value: 'Burj Al-Yahudiyya', en: 'Burj Al-Yahudiyya', district: 'Miniyeh-Danniyeh' },
  { value: 'Deir Ammar', en: 'Deir Ammar', district: 'Miniyeh-Danniyeh' },
  { value: 'Deir Nbuhe', en: 'Deir Nbuhe', district: 'Miniyeh-Danniyeh' },
  { value: 'Ezaki', en: 'Ezaki', district: 'Miniyeh-Danniyeh' },
  { value: 'Harf Al-Siyad', en: 'Harf Al-Siyad', district: 'Miniyeh-Danniyeh' },
  { value: 'Izal', en: 'Izal', district: 'Miniyeh-Danniyeh' },
  { value: 'Kfarbanin', en: 'Kfarbanin', district: 'Miniyeh-Danniyeh' },
  { value: 'Kfarhabu', en: 'Kfarhabu', district: 'Miniyeh-Danniyeh' },
  { value: 'Kfarshloun', en: 'Kfarshloun', district: 'Miniyeh-Danniyeh' },
  { value: 'Marah Al-Safira', en: 'Marah Al-Safira', district: 'Miniyeh-Danniyeh' },
  { value: 'Marah Al-Saraj', en: 'Marah Al-Saraj', district: 'Miniyeh-Danniyeh' },
  { value: 'Markabta', en: 'Markabta', district: 'Miniyeh-Danniyeh' },
  { value: 'Bkoza and Namreen', en: 'Bkoza and Namreen', district: 'Miniyeh-Danniyeh' },
  { value: 'Qorsayta', en: 'Qorsayta', district: 'Miniyeh-Danniyeh' },
  { value: 'Seer', en: 'Seer', district: 'Miniyeh-Danniyeh' },
  { value: 'Taran', en: 'Taran', district: 'Miniyeh-Danniyeh' },

  // =============================================
  // MOUNT LEBANON
  // =============================================

  // --- Chouf ---
  { value: 'Aalman and Mzaira', en: 'Aalman and Mzaira', district: 'Chouf' },
  { value: 'Ain Ouzain', en: 'Ain Ouzain', district: 'Chouf' },
  { value: 'Ain Qenye', en: 'Ain Qenye', district: 'Chouf' },
  { value: 'Ainab', en: 'Ainab (Chouf)', district: 'Chouf' },
  { value: 'Ainout', en: 'Ainout', district: 'Chouf' },
  { value: 'Aitryoun', en: 'Aitryoun', district: 'Chouf' },
  { value: 'Al Kholouniyeh', en: 'Al Kholouniyeh', district: 'Chouf' },
  { value: 'Al Khreibeh', en: 'Al Khreibeh', district: 'Chouf' },
  { value: 'Al Matallah', en: 'Al Matallah', district: 'Chouf' },
  { value: 'Al Mukhtara', en: 'Al Mukhtara', district: 'Chouf' },
  { value: 'Amatour', en: 'Amatour', district: 'Chouf' },
  { value: 'Az-Zuweiriyah', en: 'Az-Zuweiriyah', district: 'Chouf' },
  { value: 'Baadaran', en: 'Baadaran', district: 'Chouf' },
  { value: 'Baakline', en: 'Baakline', district: 'Chouf' },
  { value: 'Baassir', en: 'Baassir', district: 'Chouf' },
  { value: 'Barja', en: 'Barja', district: 'Chouf' },
  { value: 'Bassaba', en: 'Bassaba', district: 'Chouf' },
  { value: 'Bater', en: 'Bater', district: 'Chouf' },
  { value: 'Bourjein & Mrayjet', en: 'Bourjein & Mrayjet', district: 'Chouf' },
  { value: 'Btouma', en: 'Btouma', district: 'Chouf' },
  { value: 'Chehim', en: 'Chehim', district: 'Chouf' },
  { value: 'Dahr El-Mghara', en: 'Dahr El-Mghara', district: 'Chouf' },
  { value: 'Dalhoun', en: 'Dalhoun', district: 'Chouf' },
  { value: 'Daraya', en: 'Daraya', district: 'Chouf' },
  { value: 'Gharife', en: 'Gharife', district: 'Chouf' },
  { value: 'Harat Jandal', en: 'Harat Jandal', district: 'Chouf' },
  { value: 'Hasrout', en: 'Hasrout', district: 'Chouf' },
  { value: 'Jbaa', en: 'Jbaa', district: 'Chouf' },
  { value: 'Jdeideh El Chouf', en: 'Jdeideh El Chouf', district: 'Chouf' },
  { value: 'Jedra', en: 'Jedra', district: 'Chouf' },
  { value: 'Jiyeh', en: 'Jiyeh', district: 'Chouf' },
  { value: 'Joun', en: 'Joun', district: 'Chouf' },
  { value: 'Ketermaya', en: 'Ketermaya', district: 'Chouf' },
  { value: 'Maasser El Chouf', en: 'Maasser El Chouf', district: 'Chouf' },
  { value: 'Mazboud', en: 'Mazboud', district: 'Chouf' },
  { value: 'Mazraat Ad-Dahr', en: 'Mazraat Ad-Dahr', district: 'Chouf' },
  { value: 'Mazraat Ash-Shouf', en: 'Mazraat Ash-Shouf', district: 'Chouf' },
  { value: 'Mghayriyeh', en: 'Mghayriyeh', district: 'Chouf' },
  { value: 'Mristi', en: 'Mristi', district: 'Chouf' },
  { value: 'Niha', en: 'Niha', district: 'Chouf' },
  { value: 'Rmeileh', en: 'Rmeileh', district: 'Chouf' },
  { value: 'Sibline', en: 'Sibline', district: 'Chouf' },
  { value: 'Smakiah', en: 'Smakiah', district: 'Chouf' },
  { value: 'Wardanieh', en: 'Wardanieh', district: 'Chouf' },

  // --- Keserwan ---
  { value: 'Aaqbiyeh', en: 'Aaqbiyeh', district: 'Keserwan' },
  { value: 'Adma and Al-Dafnah', en: 'Adma and Al-Dafnah', district: 'Keserwan' },
  { value: 'Ain al-Rehanah', en: 'Ain al-Rehanah', district: 'Keserwan' },
  { value: 'Aintoura', en: 'Aintoura', district: 'Keserwan' },
  { value: 'Ajaltoun', en: 'Ajaltoun', district: 'Keserwan' },
  { value: 'Al Bware', en: 'Al Bware', district: 'Keserwan' },
  { value: 'Al Hasin', en: 'Al Hasin', district: 'Keserwan' },
  { value: 'Al Qulayat', en: 'Al Qulayat', district: 'Keserwan' },
  { value: 'Al Sahylih', en: 'Al Sahylih', district: 'Keserwan' },
  { value: 'Al-Azra', en: 'Al-Azra', district: 'Keserwan' },
  { value: 'Al-Ghayneh', en: 'Al-Ghayneh', district: 'Keserwan' },
  { value: 'Aramoun', en: 'Aramoun', district: 'Keserwan' },
  { value: 'Ashqout', en: 'Ashqout', district: 'Keserwan' },
  { value: 'Batha', en: 'Batha', district: 'Keserwan' },
  { value: 'Bkaatouta', en: 'Bkaatouta', district: 'Keserwan' },
  { value: 'Blouneh', en: 'Blouneh', district: 'Keserwan' },
  { value: 'Bzommar', en: 'Bzommar', district: 'Keserwan' },
  { value: 'Chehatoal', en: 'Chehatoal', district: 'Keserwan' },
  { value: 'Dalbatta', en: 'Dalbatta', district: 'Keserwan' },
  { value: 'Daroun', en: 'Daroun', district: 'Keserwan' },
  { value: 'Darya', en: 'Darya', district: 'Keserwan' },
  { value: 'DoukMakayl', en: 'DoukMakayl', district: 'Keserwan' },
  { value: 'Faitroun', en: 'Faitroun', district: 'Keserwan' },
  { value: 'Faraya', en: 'Faraya', district: 'Keserwan' },
  { value: 'Fatqa', en: 'Fatqa', district: 'Keserwan' },
  { value: 'Ghabaleh', en: 'Ghabaleh', district: 'Keserwan' },
  { value: 'Ghazir', en: 'Ghazir', district: 'Keserwan' },
  { value: 'Ghodras', en: 'Ghodras', district: 'Keserwan' },
  { value: 'Ghousta', en: 'Ghousta', district: 'Keserwan' },
  { value: 'Harajel', en: 'Harajel', district: 'Keserwan' },
  { value: 'Haytah', en: 'Haytah', district: 'Keserwan' },
  { value: 'Jdeideh', en: 'Jdeideh', district: 'Keserwan' },
  { value: 'Joueita', en: 'Joueita', district: 'Keserwan' },
  { value: 'Jounieh', en: 'Jounieh', district: 'Keserwan' },
  { value: 'Jourat Al Terms', en: 'Jourat Al Terms', district: 'Keserwan' },
  { value: 'Jourat Badran', en: 'Jourat Badran', district: 'Keserwan' },
  { value: 'Kfardbian', en: 'Kfardbian', district: 'Keserwan' },
  { value: 'Kfertay', en: 'Kfertay', district: 'Keserwan' },
  { value: 'Kfouar', en: 'Kfouar', district: 'Keserwan' },
  { value: 'Maissara', en: 'Maissara', district: 'Keserwan' },
  { value: 'Merouba', en: 'Merouba', district: 'Keserwan' },
  { value: 'Nemoura & Kfar Jarif', en: 'Nemoura & Kfar Jarif', district: 'Keserwan' },
  { value: 'Rachin', en: 'Rachin', district: 'Keserwan' },
  { value: 'Reefoun', en: 'Reefoun', district: 'Keserwan' },
  { value: 'Safra', en: 'Safra', district: 'Keserwan' },
  { value: 'Shennaya', en: 'Shennaya', district: 'Keserwan' },
  { value: 'Tabarja', en: 'Tabarja', district: 'Keserwan' },
  { value: 'Wata Al Joz', en: 'Wata Al Joz', district: 'Keserwan' },
  { value: 'Yahchouch', en: 'Yahchouch', district: 'Keserwan' },
  { value: 'Zaaitra', en: 'Zaaitra', district: 'Keserwan' },
  { value: 'Zaytoun', en: 'Zaytoun', district: 'Keserwan' },
  { value: 'Zouk Mosbeh', en: 'Zouk Mosbeh', district: 'Keserwan' },

  // --- Metn ---
  { value: 'Aeroun', en: 'Aeroun', district: 'Metn' },
  { value: 'Ain Saadeh', en: 'Ain Saadeh', district: 'Metn' },
  { value: 'Al Ghabbah', en: 'Al Ghabbah', district: 'Metn' },
  { value: 'Al Jadeeda - Al Boushriyeh', en: 'Al Jadeeda - Al Boushriyeh', district: 'Metn' },
  { value: 'Al Mansouriyah', en: 'Al Mansouriyah', district: 'Metn' },
  { value: 'Al Oyoun', en: 'Al Oyoun', district: 'Metn' },
  { value: 'Antelias', en: 'Antelias', district: 'Metn' },
  { value: 'Baabdat', en: 'Baabdat', district: 'Metn' },
  { value: 'Batgrine', en: 'Batgrine', district: 'Metn' },
  { value: 'Beit Chabab', en: 'Beit Chabab', district: 'Metn' },
  { value: 'Beit Chaar', en: 'Beit Chaar', district: 'Metn' },
  { value: 'Beit Meri', en: 'Beit Meri', district: 'Metn' },
  { value: 'Bikfaya', en: 'Bikfaya', district: 'Metn' },
  { value: 'Bourj Hammoud', en: 'Bourj Hammoud', district: 'Metn' },
  { value: 'Broumana', en: 'Broumana', district: 'Metn' },
  { value: 'Bsallim', en: 'Bsallim', district: 'Metn' },
  { value: 'Byakout', en: 'Byakout', district: 'Metn' },
  { value: 'Dahr El Sawan', en: 'Dahr El Sawan', district: 'Metn' },
  { value: 'Dawwar', en: 'Dawwar', district: 'Metn' },
  { value: 'Dbayeh', en: 'Dbayeh', district: 'Metn' },
  { value: 'Dekwaneh', en: 'Dekwaneh', district: 'Metn' },
  { value: 'Fanar', en: 'Fanar', district: 'Metn' },
  { value: 'Jal El Dib', en: 'Jal El Dib', district: 'Metn' },
  { value: 'Mar Chaaya', en: 'Mar Chaaya', district: 'Metn' },
  { value: 'Mar Musa', en: 'Mar Musa', district: 'Metn' },
  { value: 'Mazraat Yashouh', en: 'Mazraat Yashouh', district: 'Metn' },
  { value: 'Nabiheet', en: 'Nabiheet', district: 'Metn' },
  { value: 'Qanabah Baramana', en: 'Qanabah Baramana', district: 'Metn' },
  { value: 'Qornet Chehwan', en: 'Qornet Chehwan', district: 'Metn' },
  { value: 'Rabieh', en: 'Rabieh', district: 'Metn' },
  { value: 'Roumiyeh', en: 'Roumiyeh', district: 'Metn' },
  { value: 'Saqiyat Al-Misk', en: 'Saqiyat Al-Misk', district: 'Metn' },
  { value: 'Sin El Fil', en: 'Sin El Fil', district: 'Metn' },
  { value: 'Zalka', en: 'Zalka', district: 'Metn' },

  // --- Baabda ---
  { value: 'Al Kalaa', en: 'Al Kalaa', district: 'Baabda' },
  { value: 'Al Karya', en: 'Al Karya', district: 'Baabda' },
  { value: 'Al-Kosiba', en: 'Al-Kosiba', district: 'Baabda' },
  { value: 'Al-Muraijeh-Tahweta', en: 'Al-Muraijeh-Tahweta', district: 'Baabda' },
  { value: 'Al-Urbaniyah-Al-Dalibah', en: 'Al-Urbaniyah-Al-Dalibah', district: 'Baabda' },
  { value: 'Arayya', en: 'Arayya', district: 'Baabda' },
  { value: 'Arsoun', en: 'Arsoun', district: 'Baabda' },
  { value: 'Bmariam', en: 'Bmariam', district: 'Baabda' },
  { value: 'Btekhniyeh', en: 'Btekhniyeh', district: 'Baabda' },
  { value: 'Burj al-Barajneh', en: 'Burj al-Barajneh', district: 'Baabda' },
  { value: 'Bzebdine', en: 'Bzebdine', district: 'Baabda' },
  { value: 'Chiyah', en: 'Chiyah', district: 'Baabda' },
  { value: 'Deir El Harf', en: 'Deir El Harf', district: 'Baabda' },
  { value: 'Furn El Chebbak', en: 'Furn El Chebbak', district: 'Baabda' },
  { value: 'Ghobeiry', en: 'Ghobeiry', district: 'Baabda' },
  { value: 'Hammana', en: 'Hammana', district: 'Baabda' },
  { value: 'Haret Hreik', en: 'Haret Hreik', district: 'Baabda' },
  { value: 'Hasbaya (Baabda)', en: 'Hasbaya (Baabda)', district: 'Baabda' },
  { value: 'Hazmieh', en: 'Hazmieh', district: 'Baabda' },
  { value: 'Hilalia', en: 'Hilalia', district: 'Baabda' },
  { value: 'Jewar Al Haouz', en: 'Jewar Al Haouz', district: 'Baabda' },
  { value: 'Jouret Arsoun', en: 'Jouret Arsoun', district: 'Baabda' },
  { value: 'Kfarselwan', en: 'Kfarselwan', district: 'Baabda' },
  { value: 'Khuraibeh', en: 'Khuraibeh', district: 'Baabda' },
  { value: 'Qabi', en: 'Qabi', district: 'Baabda' },
  { value: 'Qornayel', en: 'Qornayel', district: 'Baabda' },
  { value: 'Qortada', en: 'Qortada', district: 'Baabda' },
  { value: 'Ras Al Harf', en: 'Ras Al Harf', district: 'Baabda' },
  { value: 'Ras al-Matn', en: 'Ras al-Matn', district: 'Baabda' },
  { value: 'Ruwayset El Ballout', en: 'Ruwayset El Ballout', district: 'Baabda' },
  { value: 'Salima', en: 'Salima', district: 'Baabda' },
  { value: 'Shabaniya', en: 'Shabaniya', district: 'Baabda' },
  { value: 'Shuwit', en: 'Shuwit', district: 'Baabda' },
  { value: 'Tarshish', en: 'Tarshish', district: 'Baabda' },

  // --- Aley ---
  { value: 'Ainab (Aley)', en: 'Ainab (Aley)', district: 'Aley' },
  { value: 'Al Bneyeh', en: 'Al Bneyeh', district: 'Aley' },
  { value: 'Al Bsatin', en: 'Al Bsatin', district: 'Aley' },
  { value: 'Al Mansouriya', en: 'Al Mansouriya', district: 'Aley' },
  { value: 'Al Mashrefah', en: 'Al Mashrefah', district: 'Aley' },
  { value: 'Batater', en: 'Batater', district: 'Aley' },
  { value: 'Baysour', en: 'Baysour', district: 'Aley' },
  { value: 'Bdeghan', en: 'Bdeghan', district: 'Aley' },
  { value: 'Bhamdoun', en: 'Bhamdoun', district: 'Aley' },
  { value: 'Chanehye', en: 'Chanehye', district: 'Aley' },
  { value: 'Charoun', en: 'Charoun', district: 'Aley' },
  { value: 'Dfoun', en: 'Dfoun', district: 'Aley' },
  { value: 'Kaifun', en: 'Kaifun', district: 'Aley' },
  { value: 'Kfarmatta', en: 'Kfarmatta', district: 'Aley' },
  { value: 'Majdlaya', en: 'Majdlaya', district: 'Aley' },
  { value: 'Remhala', en: 'Remhala', district: 'Aley' },
  { value: 'Sofar', en: 'Sofar', district: 'Aley' },

  // --- Jbeil (Byblos) ---
  { value: 'Ahmouch', en: 'Ahmouch', district: 'Jbeil' },
  { value: 'Ain Al Gowayba', en: 'Ain Al Gowayba', district: 'Jbeil' },
  { value: 'Al Aqoura', en: 'Al Aqoura', district: 'Jbeil' },
  { value: 'Al Mansaf', en: 'Al Mansaf', district: 'Jbeil' },
  { value: 'Amshit', en: 'Amshit', district: 'Jbeil' },
  { value: 'Fatri', en: 'Fatri', district: 'Jbeil' },
  { value: 'Halat', en: 'Halat', district: 'Jbeil' },
  { value: 'Jaj', en: 'Jaj', district: 'Jbeil' },
  { value: 'Jbeil', en: 'Jbeil', district: 'Jbeil' },
  { value: 'Lassa', en: 'Lassa', district: 'Jbeil' },
  { value: 'Mifouk', en: 'Mifouk', district: 'Jbeil' },
  { value: 'Nahr Ibrahim', en: 'Nahr Ibrahim', district: 'Jbeil' },
  { value: 'Qartaba', en: 'Qartaba', district: 'Jbeil' },
  { value: 'Tartij', en: 'Tartij', district: 'Jbeil' },

  // =============================================
  // AKKAR
  // =============================================

  // --- Akkar ---
  { value: 'Ad Daghlah', en: 'Ad Daghlah', district: 'Akkar' },
  { value: 'Aidmoon-Shekhlar', en: 'Aidmoon-Shekhlar', district: 'Akkar' },
  { value: 'Ain al-Dhahab', en: 'Ain al-Dhahab', district: 'Akkar' },
  { value: 'Ain al-Zayt', en: 'Ain al-Zayt', district: 'Akkar' },
  { value: 'Ain Yaaqub', en: 'Ain Yaaqub', district: 'Akkar' },
  { value: 'Akkar el-Atiqa', en: 'Akkar el-Atiqa', district: 'Akkar' },
  { value: 'Akroum', en: 'Akroum', district: 'Akkar' },
  { value: 'Al Aamair', en: 'Al Aamair', district: 'Akkar' },
  { value: 'Al Aboudiyeh', en: 'Al Aboudiyeh', district: 'Akkar' },
  { value: 'Al Awainat', en: 'Al Awainat', district: 'Akkar' },
  { value: 'Al Bireh', en: 'Al Bireh', district: 'Akkar' },
  { value: 'Al Burj', en: 'Al Burj', district: 'Akkar' },
  { value: 'Al Farid', en: 'Al Farid', district: 'Akkar' },
  { value: 'Al Hakour', en: 'Al Hakour', district: 'Akkar' },
  { value: 'Al Hishah', en: 'Al Hishah', district: 'Akkar' },
  { value: 'Al Hissa', en: 'Al Hissa', district: 'Akkar' },
  { value: 'Al Hmayra', en: 'Al Hmayra', district: 'Akkar' },
  { value: 'Al Kweikhat', en: 'Al Kweikhat', district: 'Akkar' },
  { value: 'Al Majdal', en: 'Al Majdal', district: 'Akkar' },
  { value: 'Al Maqybleh', en: 'Al Maqybleh', district: 'Akkar' },
  { value: 'Al Qariyat', en: 'Al Qariyat', district: 'Akkar' },
  { value: 'Al Qobeiyat', en: 'Al Qobeiyat', district: 'Akkar' },
  { value: 'Al Qurnah', en: 'Al Qurnah', district: 'Akkar' },
  { value: 'Al Talil', en: 'Al Talil', district: 'Akkar' },
  { value: 'Al-Ayoun', en: 'Al-Ayoun', district: 'Akkar' },
  { value: 'Al-Dabbabiya', en: 'Al-Dabbabiya', district: 'Akkar' },
  { value: 'Al-Kwashra', en: 'Al-Kwashra', district: 'Akkar' },
  { value: 'Al-Mahmara', en: 'Al-Mahmara', district: 'Akkar' },
  { value: 'Al-Maqeeta', en: 'Al-Maqeeta', district: 'Akkar' },
  { value: 'Al-Mounasseh', en: 'Al-Mounasseh', district: 'Akkar' },
  { value: 'Al-Qantara', en: 'Al-Qantara', district: 'Akkar' },
  { value: 'Al-Qarqaf', en: 'Al-Qarqaf', district: 'Akkar' },
  { value: 'Al-Rihaneya', en: 'Al-Rihaneya', district: 'Akkar' },
  { value: 'Al-Sheikh Ayyash', en: 'Al-Sheikh Ayyash', district: 'Akkar' },
  { value: 'Ammar Al-Beykat', en: 'Ammar Al-Beykat', district: 'Akkar' },
  { value: 'An Nafiseh', en: 'An Nafiseh', district: 'Akkar' },
  { value: 'An Naheriyah', en: 'An Naheriyah', district: 'Akkar' },
  { value: 'Andqet', en: 'Andqet', district: 'Akkar' },
  { value: 'Arqa', en: 'Arqa', district: 'Akkar' },
  { value: 'As Sulah', en: 'As Sulah', district: 'Akkar' },
  { value: 'Ash Shuqduf', en: 'Ash Shuqduf', district: 'Akkar' },
  { value: 'Ayun al-Ghazlan', en: 'Ayun al-Ghazlan', district: 'Akkar' },
  { value: 'Ayyat', en: 'Ayyat', district: 'Akkar' },
  { value: 'Bani Sakhr', en: 'Bani Sakhr', district: 'Akkar' },
  { value: 'Barbarah', en: 'Barbarah', district: 'Akkar' },
  { value: 'Barkaayl', en: 'Barkaayl', district: 'Akkar' },
  { value: 'Bayno - Qaboula', en: 'Bayno - Qaboula', district: 'Akkar' },
  { value: 'Bayt Ayyub', en: 'Bayt Ayyub', district: 'Akkar' },
  { value: 'Bayt Mlat', en: 'Bayt Mlat', district: 'Akkar' },
  { value: 'Bazal', en: 'Bazal', district: 'Akkar' },
  { value: 'Bazbina', en: 'Bazbina', district: 'Akkar' },
  { value: 'Bebnine', en: 'Bebnine', district: 'Akkar' },
  { value: 'Beit El Hajj', en: 'Beit El Hajj', district: 'Akkar' },
  { value: 'Beit Younes', en: 'Beit Younes', district: 'Akkar' },
  { value: 'Biqrazla', en: 'Biqrazla', district: 'Akkar' },
  { value: 'Burj Al Arab', en: 'Burj Al Arab', district: 'Akkar' },
  { value: 'Dahr Qanbar', en: 'Dahr Qanbar', district: 'Akkar' },
  { value: 'Dahr Laysina', en: 'Dahr Laysina', district: 'Akkar' },
  { value: 'Deir Dalloum', en: 'Deir Dalloum', district: 'Akkar' },
  { value: 'Deir Janine', en: 'Deir Janine', district: 'Akkar' },
  { value: 'Dura', en: 'Dura', district: 'Akkar' },
  { value: 'Dusa and Baghdad', en: 'Dusa and Baghdad', district: 'Akkar' },
  { value: 'Dweir Adwiya', en: 'Dweir Adwiya', district: 'Akkar' },
  { value: 'Eilat', en: 'Eilat', district: 'Akkar' },
  { value: 'Fassikin', en: 'Fassikin', district: 'Akkar' },
  { value: 'Fnaideq', en: 'Fnaideq', district: 'Akkar' },
  { value: 'Ghazilah', en: 'Ghazilah', district: 'Akkar' },
  { value: 'Halba', en: 'Halba', district: 'Akkar' },
  { value: 'Harrar', en: 'Harrar', district: 'Akkar' },
  { value: 'Haytla', en: 'Haytla', district: 'Akkar' },
  { value: 'Hayzouq', en: 'Hayzouq', district: 'Akkar' },
  { value: 'Houbesh', en: 'Houbesh', district: 'Akkar' },
  { value: 'Jarmnaya and Ar Rama', en: 'Jarmnaya and Ar Rama', district: 'Akkar' },
  { value: 'Jdeideh Al Juma', en: 'Jdeideh Al Juma', district: 'Akkar' },
  { value: 'Jdeideh Al Qaytaa', en: 'Jdeideh Al Qaytaa', district: 'Akkar' },
  { value: 'Jebrayel', en: 'Jebrayel', district: 'Akkar' },
  { value: 'Karm Aassfour', en: 'Karm Aassfour', district: 'Akkar' },
  { value: 'Kfarton', en: 'Kfarton', district: 'Akkar' },
  { value: 'Kharba Shar', en: 'Kharba Shar', district: 'Akkar' },
  { value: 'Kharbit Dawud', en: 'Kharbit Dawud', district: 'Akkar' },
  { value: 'Khat al Petrol', en: 'Khat al Petrol', district: 'Akkar' },
  { value: 'Khuraibeh (Akkar)', en: 'Khuraibeh', district: 'Akkar' },
  { value: 'Kousha', en: 'Kousha', district: 'Akkar' },
  { value: 'Kroom Arab', en: 'Kroom Arab', district: 'Akkar' },
  { value: 'Majdala', en: 'Majdala', district: 'Akkar' },
  { value: 'Mamna', en: 'Mamna', district: 'Akkar' },
  { value: 'Mar Touma', en: 'Mar Touma', district: 'Akkar' },
  { value: 'Mashha', en: 'Mashha', district: 'Akkar' },
  { value: 'Mazraat Bleda', en: 'Mazraat Bleda', district: 'Akkar' },
  { value: 'Minyara', en: 'Minyara', district: 'Akkar' },
  { value: 'Mishmish', en: 'Mishmish', district: 'Akkar' },
  { value: 'Munjaz', en: 'Munjaz', district: 'Akkar' },
  { value: 'Mushta Hamoud', en: 'Mushta Hamoud', district: 'Akkar' },
  { value: 'Nurah', en: 'Nurah', district: 'Akkar' },
  { value: 'Qaliyat', en: 'Qaliyat', district: 'Akkar' },
  { value: 'Qoubbet Chamra - Semqley', en: 'Qoubbet Chamra - Semqley', district: 'Akkar' },
  { value: 'Qubayyat', en: 'Qubayyat', district: 'Akkar' },
  { value: 'Quneya', en: 'Quneya', district: 'Akkar' },
  { value: 'Rahba', en: 'Rahba', district: 'Akkar' },
  { value: 'Rimah', en: 'Rimah', district: 'Akkar' },
  { value: 'Safinat Al-Qetaa', en: 'Safinat Al-Qetaa', district: 'Akkar' },
  { value: 'Safinet al-Dreib', en: 'Safinet al-Dreib', district: 'Akkar' },
  { value: 'Sandiyaneh Raydan', en: 'Sandiyaneh Raydan', district: 'Akkar' },
  { value: 'Shan', en: 'Shan', district: 'Akkar' },
  { value: 'Sharbila', en: 'Sharbila', district: 'Akkar' },
  { value: 'Sheikh Mohammad - Aadbal', en: 'Sheikh Mohammad - Aadbal', district: 'Akkar' },
  { value: 'Sheikh Taba', en: 'Sheikh Taba', district: 'Akkar' },
  { value: 'Shiddreh', en: 'Shiddreh', district: 'Akkar' },
  { value: 'Sissouk', en: 'Sissouk', district: 'Akkar' },
  { value: 'Swayseh', en: 'Swayseh', district: 'Akkar' },
  { value: 'Takrit', en: 'Takrit', district: 'Akkar' },
  { value: 'Tal Abbas Al Gharbi', en: 'Tal Abbas Al Gharbi', district: 'Akkar' },
  { value: 'Talla Washataha', en: 'Talla Washataha', district: 'Akkar' },
  { value: 'Talmaayan', en: 'Talmaayan', district: 'Akkar' },
  { value: 'Tasha', en: 'Tasha', district: 'Akkar' },
  { value: 'Wadi Al-Hawr', en: 'Wadi Al-Hawr', district: 'Akkar' },
  { value: 'Wadi al-Jamus', en: 'Wadi al-Jamus', district: 'Akkar' },
  { value: 'Wadi Khalid', en: 'Wadi Khalid', district: 'Akkar' },
  { value: 'Zawarib', en: 'Zawarib', district: 'Akkar' },
  { value: 'Zouk al-Hssayne', en: 'Zouk al-Hssayne', district: 'Akkar' },
  { value: 'Zouk Hadara', en: 'Zouk Hadara', district: 'Akkar' },

  // =============================================
  // SOUTH LEBANON
  // =============================================

  // --- Sidon ---
  { value: 'Aabra', en: 'Aabra', district: 'Sidon' },
  { value: 'Adloun', en: 'Adloun', district: 'Sidon' },
  { value: 'Adousiyeh', en: 'Adousiyeh', district: 'Sidon' },
  { value: 'Ain Eddelb', en: 'Ain Eddelb', district: 'Sidon' },
  { value: 'Al Bisariyah', en: 'Al Bisariyah', district: 'Sidon' },
  { value: 'Al Hilaliyah', en: 'Al Hilaliyah', district: 'Sidon' },
  { value: 'Al Lubiyah', en: 'Al Lubiyah', district: 'Sidon' },
  { value: 'Al Marwaniyah', en: 'Al Marwaniyah', district: 'Sidon' },
  { value: 'Al Mayy Wal Mayy', en: 'Al Mayy Wal Mayy', district: 'Sidon' },
  { value: 'Al Quryah', en: 'Al Quryah', district: 'Sidon' },
  { value: 'An Najariyah', en: 'An Najariyah', district: 'Sidon' },
  { value: 'Anqoun', en: 'Anqoun', district: 'Sidon' },
  { value: 'Ansariyah', en: 'Ansariyah', district: 'Sidon' },
  { value: 'Babliyeh', en: 'Babliyeh', district: 'Sidon' },
  { value: 'Baksata', en: 'Baksata', district: 'Sidon' },
  { value: 'Baramiyeh', en: 'Baramiyeh', district: 'Sidon' },
  { value: 'Derb Essim', en: 'Derb Essim', district: 'Sidon' },
  { value: 'Ghassaniyeh', en: 'Ghassaniyeh', district: 'Sidon' },
  { value: 'Ghazieh', en: 'Ghazieh', district: 'Sidon' },
  { value: 'Haret Saida', en: 'Haret Saida', district: 'Sidon' },
  { value: 'Kawthariyat al-Siyad', en: 'Kawthariyat al-Siyad', district: 'Sidon' },
  { value: 'Khartoum', en: 'Khartoum', district: 'Sidon' },
  { value: 'Majdalyoun', en: 'Majdalyoun', district: 'Sidon' },
  { value: 'Mghdousheh', en: 'Mghdousheh', district: 'Sidon' },
  { value: 'Qaqaiyyat al-Sanawbar', en: 'Qaqaiyyat al-Sanawbar', district: 'Sidon' },
  { value: 'Saksakiye', en: 'Saksakiye', district: 'Sidon' },
  { value: 'Salehieh', en: 'Salehieh', district: 'Sidon' },
  { value: 'Sarafand', en: 'Sarafand', district: 'Sidon' },
  { value: 'Sidon', en: 'Sidon', district: 'Sidon' },
  { value: 'Taffahita', en: 'Taffahita', district: 'Sidon' },
  { value: 'Tanbourit', en: 'Tanbourit', district: 'Sidon' },

  // --- Tyre ---
  { value: 'Ain Baal', en: 'Ain Baal', district: 'Tyre' },
  { value: 'Al Abbasiyah', en: 'Al Abbasiyah', district: 'Tyre' },
  { value: 'Al Bayyad', en: 'Al Bayyad', district: 'Tyre' },
  { value: 'Al Bazuriyah', en: 'Al Bazuriyah', district: 'Tyre' },
  { value: 'Al Burghliye', en: 'Al Burghliye', district: 'Tyre' },
  { value: 'Al Bustan', en: 'Al Bustan', district: 'Tyre' },
  { value: 'Al Hamiri', en: 'Al Hamiri', district: 'Tyre' },
  { value: 'Al Hlousiyeh', en: 'Al Hlousiyeh', district: 'Tyre' },
  { value: 'Al Jibbin', en: 'Al Jibbin', district: 'Tyre' },
  { value: 'Al Mansouri', en: 'Al Mansouri', district: 'Tyre' },
  { value: 'Al Qulaylah', en: 'Al Qulaylah', district: 'Tyre' },
  { value: 'Al Shaatiye', en: 'Al Shaatiye', district: 'Tyre' },
  { value: 'Alhinya', en: 'Alhinya', district: 'Tyre' },
  { value: 'Alkanisa', en: 'Alkanisa', district: 'Tyre' },
  { value: 'Alma Ash Shaaab', en: 'Alma Ash Shaaab', district: 'Tyre' },
  { value: 'Alzahira', en: 'Alzahira', district: 'Tyre' },
  { value: 'An Naqoura', en: 'An Naqoura', district: 'Tyre' },
  { value: 'Arzoun', en: 'Arzoun', district: 'Tyre' },
  { value: 'Aytit', en: 'Aytit', district: 'Tyre' },
  { value: 'Batoulieh', en: 'Batoulieh', district: 'Tyre' },
  { value: 'Bedeas', en: 'Bedeas', district: 'Tyre' },
  { value: 'Bourj Al Shamali', en: 'Bourj Al Shamali', district: 'Tyre' },
  { value: 'Bourj Rahhal', en: 'Bourj Rahhal', district: 'Tyre' },
  { value: 'Deir Amess', en: 'Deir Amess', district: 'Tyre' },
  { value: 'Deir Keifa', en: 'Deir Keifa', district: 'Tyre' },
  { value: 'Deir Qanoun En Nahr', en: 'Deir Qanoun En Nahr', district: 'Tyre' },
  { value: 'Deir Qanoun Ras Al Ain', en: 'Deir Qanoun Ras Al Ain', district: 'Tyre' },
  { value: 'Dirdghayya', en: 'Dirdghayya', district: 'Tyre' },
  { value: 'Hinawiye', en: 'Hinawiye', district: 'Tyre' },
  { value: 'Jabal Albutm', en: 'Jabal Albutm', district: 'Tyre' },
  { value: 'Jannata', en: 'Jannata', district: 'Tyre' },
  { value: 'Maaroub', en: 'Maaroub', district: 'Tyre' },
  { value: 'Majadel', en: 'Majadel', district: 'Tyre' },
  { value: 'Majdalzoun', en: 'Majdalzoun', district: 'Tyre' },
  { value: 'Marwahine', en: 'Marwahine', district: 'Tyre' },
  { value: 'Mazraat Moshref', en: 'Mazraat Moshref', district: 'Tyre' },
  { value: 'Mearka', en: 'Mearka', district: 'Tyre' },
  { value: 'Qana', en: 'Qana', district: 'Tyre' },
  { value: 'Ramadiyeh', en: 'Ramadiyeh', district: 'Tyre' },
  { value: 'Rashkananiye', en: 'Rashkananiye', district: 'Tyre' },
  { value: 'Shahour', en: 'Shahour', district: 'Tyre' },
  { value: 'Shaykhain', en: 'Shaykhain', district: 'Tyre' },
  { value: 'Shmaa', en: 'Shmaa', district: 'Tyre' },
  { value: 'Sour', en: 'Sour', district: 'Tyre' },
  { value: 'Srifa', en: 'Srifa', district: 'Tyre' },
  { value: 'Tir Dibba', en: 'Tir Dibba', district: 'Tyre' },
  { value: 'Tura', en: 'Tura', district: 'Tyre' },
  { value: 'Tyr Felsay', en: 'Tyr Felsay', district: 'Tyre' },
  { value: 'Yanouh', en: 'Yanouh', district: 'Tyre' },
  { value: 'Yarine', en: 'Yarine', district: 'Tyre' },
  { value: 'Zabkin', en: 'Zabkin', district: 'Tyre' },

  // --- Jezzine ---
  { value: 'Aarai', en: 'Aarai', district: 'Jezzine' },
  { value: 'Al Maknouneh', en: 'Al Maknouneh', district: 'Jezzine' },
  { value: 'Al Midan', en: 'Al Midan', district: 'Jezzine' },
  { value: 'Al-Eishiyeh', en: 'Al-Eishiyeh', district: 'Jezzine' },
  { value: 'Al-Hamssiyeh', en: 'Al-Hamssiyeh', district: 'Jezzine' },
  { value: 'Al-Louwayzeh', en: 'Al-Louwayzeh', district: 'Jezzine' },
  { value: 'Al-Rayhan', en: 'Al-Rayhan', district: 'Jezzine' },
  { value: 'Aramta', en: 'Aramta', district: 'Jezzine' },
  { value: 'Azour', en: 'Azour', district: 'Jezzine' },
  { value: 'Bkassine', en: 'Bkassine', district: 'Jezzine' },
  { value: 'Bnouhate', en: 'Bnouhate', district: 'Jezzine' },
  { value: 'Bteddine Al-Laqch', en: 'Bteddine Al-Laqch', district: 'Jezzine' },
  { value: 'Haytoura', en: 'Haytoura', district: 'Jezzine' },
  { value: 'Jezzine', en: 'Jezzine', district: 'Jezzine' },
  { value: 'Jrania', en: 'Jrania', district: 'Jezzine' },
  { value: 'Karkha', en: 'Karkha', district: 'Jezzine' },
  { value: 'Kfar Jirra', en: 'Kfar Jirra', district: 'Jezzine' },
  { value: 'Kfarfalous', en: 'Kfarfalous', district: 'Jezzine' },
  { value: 'Labaa', en: 'Labaa', district: 'Jezzine' },
  { value: 'Majdal', en: 'Majdal', district: 'Jezzine' },
  { value: 'Mchmoush', en: 'Mchmoush', district: 'Jezzine' },
  { value: 'Mleih', en: 'Mleih', district: 'Jezzine' },
  { value: 'Qaitouli', en: 'Qaitouli', district: 'Jezzine' },
  { value: 'Qattin and Haidab', en: 'Qattin and Haidab', district: 'Jezzine' },
  { value: 'Raymat and Shqadif', en: 'Raymat and Shqadif', district: 'Jezzine' },
  { value: 'Roum', en: 'Roum', district: 'Jezzine' },
  { value: 'Sabah', en: 'Sabah', district: 'Jezzine' },
  { value: 'Safarayya', en: 'Safarayya', district: 'Jezzine' },
  { value: 'Saniyyeh', en: 'Saniyyeh', district: 'Jezzine' },
  { value: 'Sidon (Jezzine)', en: 'Sidon (Jezzine)', district: 'Jezzine' },
  { value: 'Sijd', en: 'Sijd', district: 'Jezzine' },
  { value: 'Wadi Jezzine', en: 'Wadi Jezzine', district: 'Jezzine' },
  { value: 'Zahlta', en: 'Zahlta', district: 'Jezzine' },

  // =============================================
  // NABATIEH
  // =============================================

  // --- Nabatieh ---
  { value: 'Aaba (Nabatieh)', en: 'Aaba', district: 'Nabatieh' },
  { value: 'Adchit', en: 'Adchit', district: 'Nabatieh' },
  { value: 'Ain Qana', en: 'Ain Qana', district: 'Nabatieh' },
  { value: 'Al Kfour', en: 'Al Kfour', district: 'Nabatieh' },
  { value: 'Al Qsaybeh', en: 'Al Qsaybeh', district: 'Nabatieh' },
  { value: 'Al-Sharkiya', en: 'Al-Sharkiya', district: 'Nabatieh' },
  { value: 'Ansar', en: 'Ansar', district: 'Nabatieh' },
  { value: 'Arabsalim', en: 'Arabsalim', district: 'Nabatieh' },
  { value: 'Arnoun', en: 'Arnoun', district: 'Nabatieh' },
  { value: 'Bariqaa', en: 'Bariqaa', district: 'Nabatieh' },
  { value: 'Choukeen', en: 'Choukeen', district: 'Nabatieh' },
  { value: 'Deir Al-Zahrani', en: 'Deir Al-Zahrani', district: 'Nabatieh' },
  { value: 'Doueir', en: 'Doueir', district: 'Nabatieh' },
  { value: 'Ezza', en: 'Ezza', district: 'Nabatieh' },
  { value: 'Habbouch', en: 'Habbouch', district: 'Nabatieh' },
  { value: 'Harouf', en: 'Harouf', district: 'Nabatieh' },
  { value: 'Houmine Al-Fawqa', en: 'Houmine Al-Fawqa', district: 'Nabatieh' },
  { value: 'Houmine Al-Tahta', en: 'Houmine Al-Tahta', district: 'Nabatieh' },
  { value: 'Jargea', en: 'Jargea', district: 'Nabatieh' },
  { value: 'Jbaa (Nabatieh)', en: 'Jbaa', district: 'Nabatieh' },
  { value: 'Jibchit', en: 'Jibchit', district: 'Nabatieh' },
  { value: 'Kaakaiye Bridge', en: 'Kaakaiye Bridge', district: 'Nabatieh' },
  { value: 'Kafr Fila', en: 'Kafr Fila', district: 'Nabatieh' },
  { value: 'Kafr Ruman', en: 'Kafr Ruman', district: 'Nabatieh' },
  { value: 'Kafr Sir', en: 'Kafr Sir', district: 'Nabatieh' },
  { value: 'Kafr Tibnit', en: 'Kafr Tibnit', district: 'Nabatieh' },
  { value: 'Mayfadoun', en: 'Mayfadoun', district: 'Nabatieh' },
  { value: 'Nabatieh', en: 'Nabatieh', district: 'Nabatieh' },
  { value: 'Nabatieh Al-Fawqa', en: 'Nabatieh Al-Fawqa', district: 'Nabatieh' },
  { value: 'Nemriye', en: 'Nemriye', district: 'Nabatieh' },
  { value: 'Rumine', en: 'Rumine', district: 'Nabatieh' },
  { value: 'Sair Al-Gharbiya', en: 'Sair Al-Gharbiya', district: 'Nabatieh' },
  { value: 'Sarbah', en: 'Sarbah', district: 'Nabatieh' },
  { value: 'Seen', en: 'Seen', district: 'Nabatieh' },
  { value: 'Yohmor', en: 'Yohmor', district: 'Nabatieh' },
  { value: 'Zawtar Al-Gharbiya', en: 'Zawtar Al-Gharbiya', district: 'Nabatieh' },
  { value: 'Zawtar Al-Sharkiya', en: 'Zawtar Al-Sharkiya', district: 'Nabatieh' },
  { value: 'Zefta', en: 'Zefta', district: 'Nabatieh' },
  { value: 'Zibdeen', en: 'Zibdeen', district: 'Nabatieh' },

  // --- Bint Jbeil ---
  { value: 'Ainata', en: 'Ainata', district: 'Bint Jbeil' },
  { value: 'Aita Al-Jabal', en: 'Aita Al-Jabal', district: 'Bint Jbeil' },
  { value: 'Aitroun', en: 'Aitroun', district: 'Bint Jbeil' },
  { value: 'Al Tireh', en: 'Al Tireh', district: 'Bint Jbeil' },
  { value: 'Baraachit', en: 'Baraachit', district: 'Bint Jbeil' },
  { value: 'Beit Leif', en: 'Beit Leif', district: 'Bint Jbeil' },
  { value: 'Bint Jbeil', en: 'Bint Jbeil', district: 'Bint Jbeil' },
  { value: 'Deir Antar', en: 'Deir Antar', district: 'Bint Jbeil' },
  { value: 'Haris', en: 'Haris', district: 'Bint Jbeil' },
  { value: 'Jammijmeh', en: 'Jammijmeh', district: 'Bint Jbeil' },
  { value: 'Kafr Dounin', en: 'Kafr Dounin', district: 'Bint Jbeil' },
  { value: 'Kounine', en: 'Kounine', district: 'Bint Jbeil' },
  { value: 'Kufra', en: 'Kufra', district: 'Bint Jbeil' },
  { value: 'Maroun Ras El', en: 'Maroun Ras El', district: 'Bint Jbeil' },
  { value: 'Qalawayh', en: 'Qalawayh', district: 'Bint Jbeil' },
  { value: 'Safad El Batikh', en: 'Safad El Batikh', district: 'Bint Jbeil' },
  { value: 'Tebnine', en: 'Tebnine', district: 'Bint Jbeil' },
  { value: 'Yater', en: 'Yater', district: 'Bint Jbeil' },

  // --- Marjeyoun ---
  { value: 'Ain Qenya (Marjeyoun)', en: 'Ain Qenya', district: 'Marjeyoun' },
  { value: 'Al-Kafr (Marjeyoun)', en: 'Al-Kafr', district: 'Marjeyoun' },
  { value: 'Al-Khalwat (Marjeyoun)', en: 'Al-Khalwat', district: 'Marjeyoun' },
  { value: 'Hasbaya (Marjeyoun)', en: 'Hasbaya', district: 'Marjeyoun' },
  { value: 'Kawkaba (Marjeyoun)', en: 'Kawkaba', district: 'Marjeyoun' },
  { value: 'Marj al-Zuhur (Marjeyoun)', en: 'Marj al-Zuhur', district: 'Marjeyoun' },
  { value: 'Mimas (Marjeyoun)', en: 'Mimas', district: 'Marjeyoun' },
  { value: 'Shwaya (Marjeyoun)', en: 'Shwaya', district: 'Marjeyoun' },

  // --- Hasbaya ---
  { value: 'Ain Qenya (Hasbaya)', en: 'Ain Qenya', district: 'Hasbaya' },
  { value: 'Al-Fardis', en: 'Al-Fardis', district: 'Hasbaya' },
  { value: 'Al-Habariyah', en: 'Al-Habariyah', district: 'Hasbaya' },
  { value: 'Al-Kafr (Hasbaya)', en: 'Al-Kafr', district: 'Hasbaya' },
  { value: 'Al-Khalwat (Hasbaya)', en: 'Al-Khalwat', district: 'Hasbaya' },
  { value: 'Hasbaya', en: 'Hasbaya', district: 'Hasbaya' },
  { value: 'Kafr Hammam', en: 'Kafr Hammam', district: 'Hasbaya' },
  { value: 'Kafr Shuba', en: 'Kafr Shuba', district: 'Hasbaya' },
  { value: 'Kawkaba (Hasbaya)', en: 'Kawkaba', district: 'Hasbaya' },
  { value: 'Majideyah wa Marieh', en: 'Majideyah wa Marieh', district: 'Hasbaya' },
  { value: 'Marj al-Zuhur (Hasbaya)', en: 'Marj al-Zuhur', district: 'Hasbaya' },
  { value: 'Mimas (Hasbaya)', en: 'Mimas', district: 'Hasbaya' },
  { value: 'Rashaya al-Fukhar', en: 'Rashaya al-Fukhar', district: 'Hasbaya' },
  { value: 'Shebaa', en: 'Shebaa', district: 'Hasbaya' },
  { value: 'Shwaya (Hasbaya)', en: 'Shwaya', district: 'Hasbaya' },

  // =============================================
  // BEQAA
  // =============================================

  // --- Zahle ---
  { value: 'Abilh', en: 'Abilh', district: 'Zahle' },
  { value: 'Ain Kafarzabad', en: 'Ain Kafarzabad', district: 'Zahle' },
  { value: 'Ali Al-Nahri', en: 'Ali Al-Nahri', district: 'Zahle' },
  { value: 'Bar Elias', en: 'Bar Elias', district: 'Zahle' },
  { value: 'Bawarj', en: 'Bawarj', district: 'Zahle' },
  { value: 'Chatura', en: 'Chatura', district: 'Zahle' },
  { value: 'Deir Al-Ghazal', en: 'Deir Al-Ghazal', district: 'Zahle' },
  { value: 'Ferzol', en: 'Ferzol', district: 'Zahle' },
  { value: 'Hay Al-Fikani', en: 'Hay Al-Fikani', district: 'Zahle' },
  { value: 'Hazerta', en: 'Hazerta', district: 'Zahle' },
  { value: 'Hosh Moussa', en: 'Hosh Moussa', district: 'Zahle' },
  { value: 'Kfarzabad', en: 'Kfarzabad', district: 'Zahle' },
  { value: 'Maaloula and Taanayel', en: 'Maaloula and Taanayel', district: 'Zahle' },
  { value: 'Majdal Anjar', en: 'Majdal Anjar', district: 'Zahle' },
  { value: 'Makse', en: 'Makse', district: 'Zahle' },
  { value: 'Massa', en: 'Massa', district: 'Zahle' },
  { value: 'Mrayjet (Zahle)', en: 'Mrayjet', district: 'Zahle' },
  { value: 'Nasiriya', en: 'Nasiriya', district: 'Zahle' },
  { value: 'Niha (Zahle)', en: 'Niha', district: 'Zahle' },
  { value: 'Qob Elias', en: 'Qob Elias', district: 'Zahle' },
  { value: 'Qousaya', en: 'Qousaya', district: 'Zahle' },
  { value: 'Riak', en: 'Riak', district: 'Zahle' },
  { value: 'Riyat', en: 'Riyat', district: 'Zahle' },
  { value: 'Saadnayel', en: 'Saadnayel', district: 'Zahle' },
  { value: 'Talabayya', en: 'Talabayya', district: 'Zahle' },
  { value: 'Trebil', en: 'Trebil', district: 'Zahle' },
  { value: 'Zahle', en: 'Zahle', district: 'Zahle' },

  // --- Western Beqaa ---
  { value: 'Aana', en: 'Aana', district: 'Western Beqaa' },
  { value: 'Ain El Tinah', en: 'Ain El Tinah', district: 'Western Beqaa' },
  { value: 'Ain Zabda', en: 'Ain Zabda', district: 'Western Beqaa' },
  { value: 'Al Manara', en: 'Al Manara', district: 'Western Beqaa' },
  { value: 'Al Mansoura', en: 'Al Mansoura', district: 'Western Beqaa' },
  { value: 'Al Rawda', en: 'Al Rawda', district: 'Western Beqaa' },
  { value: 'Al-Khiyara', en: 'Al-Khiyara', district: 'Western Beqaa' },
  { value: 'Al-Muruj', en: 'Al-Muruj', district: 'Western Beqaa' },
  { value: 'Al-Sawiri', en: 'Al-Sawiri', district: 'Western Beqaa' },
  { value: 'Ameq', en: 'Ameq', district: 'Western Beqaa' },
  { value: 'Aytanit', en: 'Aytanit', district: 'Western Beqaa' },
  { value: "Ba'loul", en: "Ba'loul", district: 'Western Beqaa' },
  { value: "Bab Mare'", en: "Bab Mare'", district: 'Western Beqaa' },
  { value: 'Gaza', en: 'Gaza', district: 'Western Beqaa' },
  { value: 'Hosh Al-Harimeh', en: 'Hosh Al-Harimeh', district: 'Western Beqaa' },
  { value: 'Jaba Jenin', en: 'Jaba Jenin', district: 'Western Beqaa' },
  { value: 'Kafraya', en: 'Kafraya', district: 'Western Beqaa' },
  { value: 'Kamid Al-Lawz', en: 'Kamid Al-Lawz', district: 'Western Beqaa' },
  { value: 'Khirbet Qanafar', en: 'Khirbet Qanafar', district: 'Western Beqaa' },
  { value: 'Lala', en: 'Lala', district: 'Western Beqaa' },
  { value: 'Lubya', en: 'Lubya', district: 'Western Beqaa' },
  { value: 'Mashgharah', en: 'Mashgharah', district: 'Western Beqaa' },
  { value: 'Midoun and Lussia', en: 'Midoun and Lussia', district: 'Western Beqaa' },
  { value: 'Qarawat Bani Hassan', en: 'Qarawat Bani Hassan', district: 'Western Beqaa' },
  { value: 'Qilya', en: 'Qilya', district: 'Western Beqaa' },
  { value: 'Saghbin', en: 'Saghbin', district: 'Western Beqaa' },
  { value: 'Sahmara', en: 'Sahmara', district: 'Western Beqaa' },
  { value: "Sultan Ya'qub", en: "Sultan Ya'qub", district: 'Western Beqaa' },
  { value: 'Tall Dzanoub', en: 'Tall Dzanoub', district: 'Western Beqaa' },
  { value: 'Yahmar', en: 'Yahmar', district: 'Western Beqaa' },
  { value: 'Zalaya', en: 'Zalaya', district: 'Western Beqaa' },

  // --- Rachaya ---
  { value: 'Ain Arab', en: 'Ain Arab', district: 'Rachaya' },
  { value: 'Ain Ata', en: 'Ain Ata', district: 'Rachaya' },
  { value: 'Ain Harsha', en: 'Ain Harsha', district: 'Rachaya' },
  { value: 'Al-Aqaba', en: 'Al-Aqaba', district: 'Rachaya' },
  { value: 'Al-Bireh (Rachaya)', en: 'Al-Bireh', district: 'Rachaya' },
  { value: 'Al-Muheithrah', en: 'Al-Muheithrah', district: 'Rachaya' },
  { value: 'Al-Rafid', en: 'Al-Rafid', district: 'Rachaya' },
  { value: 'Beit Lahia', en: 'Beit Lahia', district: 'Rachaya' },
  { value: 'Bkaa', en: 'Bkaa', district: 'Rachaya' },
  { value: 'Bkifa', en: 'Bkifa', district: 'Rachaya' },
  { value: 'Deir Al-Ashayer', en: 'Deir Al-Ashayer', district: 'Rachaya' },
  { value: 'Eita Al-Fakhar', en: 'Eita Al-Fakhar', district: 'Rachaya' },
  { value: 'Eyha', en: 'Eyha', district: 'Rachaya' },
  { value: 'Halawa', en: 'Halawa', district: 'Rachaya' },
  { value: 'Hosh Al-Qanaba', en: 'Hosh Al-Qanaba', district: 'Rachaya' },
  { value: 'Kafr Danis', en: 'Kafr Danis', district: 'Rachaya' },
  { value: 'Kafr Mashki', en: 'Kafr Mashki', district: 'Rachaya' },
  { value: 'Kafr Qouq', en: 'Kafr Qouq', district: 'Rachaya' },
  { value: 'Kawkaba (Rachaya)', en: 'Kawkaba', district: 'Rachaya' },
  { value: 'Khirbet Rouha', en: 'Khirbet Rouha', district: 'Rachaya' },
  { value: 'Majdal Bani Fadel', en: 'Majdal Bani Fadel', district: 'Rachaya' },
  { value: 'Mudawwara', en: 'Mudawwara', district: 'Rachaya' },
  { value: 'Rashaya', en: 'Rashaya', district: 'Rachaya' },
  { value: 'Tannourine (Rachaya)', en: 'Tannourine', district: 'Rachaya' },
  { value: 'Yanta', en: 'Yanta', district: 'Rachaya' },
  { value: 'Zahr Al-Ahmar', en: 'Zahr Al-Ahmar', district: 'Rachaya' },

  // =============================================
  // BAALBEK-HERMEL
  // =============================================

  // --- Baalbek ---
  { value: 'Ainata (Baalbek)', en: 'Ainata', district: 'Baalbek' },
  { value: 'Al Ansar', en: 'Al Ansar', district: 'Baalbek' },
  { value: 'Al Khreibeh', en: 'Al Khreibeh', district: 'Baalbek' },
  { value: 'Al Khudr', en: 'Al Khudr', district: 'Baalbek' },
  { value: 'Al Ram and Al Jubayniyah', en: 'Al Ram and Al Jubayniyah', district: 'Baalbek' },
  { value: 'Al Tawfiqiyah', en: 'Al Tawfiqiyah', district: 'Baalbek' },
  { value: 'Al Zarazir', en: 'Al Zarazir', district: 'Baalbek' },
  { value: 'Al-Ain', en: 'Al-Ain', district: 'Baalbek' },
  { value: 'Al-Laboue', en: 'Al-Laboue', district: 'Baalbek' },
  { value: 'Al-Nabi Othman', en: 'Al-Nabi Othman', district: 'Baalbek' },
  { value: 'Al-Nabi Sheet', en: 'Al-Nabi Sheet', district: 'Baalbek' },
  { value: 'Al-Saeeda', en: 'Al-Saeeda', district: 'Baalbek' },
  { value: 'Baalbek', en: 'Baalbek', district: 'Baalbek' },
  { value: 'Barqa', en: 'Barqa', district: 'Baalbek' },
  { value: 'Bdenayel', en: 'Bdenayel', district: 'Baalbek' },
  { value: 'Beit Shama', en: 'Beit Shama', district: 'Baalbek' },
  { value: 'Bishwat', en: 'Bishwat', district: 'Baalbek' },
  { value: 'Boudai and Al Alaqa', en: 'Boudai and Al Alaqa', district: 'Baalbek' },
  { value: 'Brital', en: 'Brital', district: 'Baalbek' },
  { value: 'Btedai', en: 'Btedai', district: 'Baalbek' },
  { value: 'Deir Al Ahmar', en: 'Deir Al Ahmar', district: 'Baalbek' },
  { value: 'Douris', en: 'Douris', district: 'Baalbek' },
  { value: 'Flawi', en: 'Flawi', district: 'Baalbek' },
  { value: 'Hadath Baalbek', en: 'Hadath Baalbek', district: 'Baalbek' },
  { value: 'Halabat', en: 'Halabat', district: 'Baalbek' },
  { value: 'Harbata', en: 'Harbata', district: 'Baalbek' },
  { value: 'Hawsh Al Nabi', en: 'Hawsh Al Nabi', district: 'Baalbek' },
  { value: 'Hawsh Al Rafiqah', en: 'Hawsh Al Rafiqah', district: 'Baalbek' },
  { value: 'Hawsh Saneed', en: 'Hawsh Saneed', district: 'Baalbek' },
  { value: 'Hazin', en: 'Hazin', district: 'Baalbek' },
  { value: 'Houch Berda', en: 'Houch Berda', district: 'Baalbek' },
  { value: 'Houch Tel Safiye', en: 'Houch Tel Safiye', district: 'Baalbek' },
  { value: 'Hurit Alaa', en: 'Hurit Alaa', district: 'Baalbek' },
  { value: 'Iaat', en: 'Iaat', district: 'Baalbek' },
  { value: "Jaba'a (Baalbek)", en: "Jaba'a", district: 'Baalbek' },
  { value: 'Jabule', en: 'Jabule', district: 'Baalbek' },
  { value: 'Jinta', en: 'Jinta', district: 'Baalbek' },
  { value: 'Kfardan', en: 'Kfardan', district: 'Baalbek' },
  { value: "Ma'arabun", en: "Ma'arabun", district: 'Baalbek' },
  { value: 'Majdaloun', en: 'Majdaloun', district: 'Baalbek' },
  { value: 'Mqneh', en: 'Mqneh', district: 'Baalbek' },
  { value: 'Nabha Al Dumdum', en: 'Nabha Al Dumdum', district: 'Baalbek' },
  { value: 'Nabha Al Mahfara', en: 'Nabha Al Mahfara', district: 'Baalbek' },
  { value: 'Nabha Al Qadam', en: 'Nabha Al Qadam', district: 'Baalbek' },
  { value: 'Nahle', en: 'Nahle', district: 'Baalbek' },
  { value: 'Qaleela and Harfoush', en: 'Qaleela and Harfoush', district: 'Baalbek' },
  { value: 'Qarah', en: 'Qarah', district: 'Baalbek' },
  { value: 'Qasr Naba', en: 'Qasr Naba', district: 'Baalbek' },
  { value: 'Sareen Al-Fawqa', en: 'Sareen Al-Fawqa', district: 'Baalbek' },
  { value: 'Serain Al Tahta', en: 'Serain Al Tahta', district: 'Baalbek' },
  { value: 'Shaath', en: 'Shaath', district: 'Baalbek' },
  { value: 'Shamstaar', en: 'Shamstaar', district: 'Baalbek' },
  { value: 'Talya', en: 'Talya', district: 'Baalbek' },
  { value: 'Tannin Al Foqa', en: 'Tannin Al Foqa', district: 'Baalbek' },
  { value: 'Tannin Al Tahta', en: 'Tannin Al Tahta', district: 'Baalbek' },
  { value: 'Tariya', en: 'Tariya', district: 'Baalbek' },
  { value: "Wadi Fa'rah", en: "Wadi Fa'rah", district: 'Baalbek' },
  { value: 'Yunin', en: 'Yunin', district: 'Baalbek' },
  { value: 'Zabud', en: 'Zabud', district: 'Baalbek' },

  // --- Hermel ---
  { value: 'Al Hermel', en: 'Al Hermel', district: 'Hermel' },
  { value: 'Al Kawakh', en: 'Al Kawakh', district: 'Hermel' },
  { value: 'Al Qasr', en: 'Al Qasr', district: 'Hermel' },
  { value: 'Al Shawagir', en: 'Al Shawagir', district: 'Hermel' },
  { value: 'Fissan', en: 'Fissan', district: 'Hermel' },
  { value: 'Jawar Al Hashish', en: 'Jawar Al Hashish', district: 'Hermel' },
];

/**
 * Get districts for a given governorate.
 * For Beirut/Akkar (single district), returns that one district.
 */
export function getDistrictsForGovernorate(governorate) {
  return DISTRICTS.filter((d) => d.governorate === governorate);
}

/**
 * Get municipalities for a given district.
 * Returns empty until municipality data is provided.
 */
export function getMunicipalitiesForDistrict(district) {
  return MUNICIPALITIES.filter((m) => m.district === district);
}

/**
 * Check if a governorate has only one district (auto-select it).
 */
export function isSingleDistrictGovernorate(governorate) {
  return getDistrictsForGovernorate(governorate).length === 1;
}